### ISSUE TITLE
extension with cf wont load
aniyomi use another approach. 

### ISSUE THREAD

**Issue by MaiSan9999** [rebelonion/Dantotsu#1]

**Comment by rebelonion** [comment]
Please give info on your problem

**Comment by MaiSan9999** [comment]
Uploading Screen Record_2023-10-18-19-07-22.mp4…

sorry accidentally closed issue without realizing.

**Comment by rebelonion** [comment]
thanks for the report
I'll look into adding that

**Comment by rebelonion** [comment]
added in beta
