### ISSUE TITLE
Extension settings 

### ISSUE THREAD

**Issue by dinkusoni** [rebelonion/Dantotsu#10]
Can you add extension settings like aniyomi because of domain change dub and sub, quality change

**Comment by rebelonion** [comment]
currently planned

**Comment by dinkusoni** [comment]
> currently planned

Thanks for working on this i am hoping for your app to become best of the best

**Comment by dinkusoni** [comment]
For example all anime extension settings have domain change, dub and sub, video quality default settings can you add those

**Comment by rebelonion** [comment]
yep
that's the plan

**Comment by rebelonion** [comment]
the beta version of the app now has extension settings

**Comment by dinkusoni** [comment]
> the beta version of the app now has extension settings

Oh i will test beta yum yum

**Comment by rebelonion** [comment]
Will be done in the next update
