### ISSUE TITLE
Bug: After reading 2 pages in manga app crashes.

### ISSUE THREAD

**Issue by Subbarao6338** [rebelonion/Dantotsu#103]
Bug: After reading 2 pages in manga app crashes.
While watching a video, after 2 to 3 min or skip , app crashes again.
Please fix this

**Comment by rebelonion** [comment]
You're going to have to give more information than that.

Always or just sometimes?
Every extension?
Does something trigger it?
Android version?
Have you tried clearing cache/data and reinstalling the app?
What version of app?

This doesn't happen to anyone else so there's something different about the way you are using the app.

**Comment by Subbarao6338** [comment]
Always
Checked 2 to 3 extensions but same
Android 13, miui 14
Tried clear the cache, but same
Both stable and beta 2.0.0 version

**Comment by rebelonion** [comment]
this is very weird
you're not using a custom rom by chance?

**Comment by Subbarao6338** [comment]
No not at all.
Poco f5 MiUi 14 Android 13 official india

**Comment by rebelonion** [comment]
The weirdest part is I'm getting no crash reports sent from that, so it makes me wonder if something external is killing the app.
You're the first person with this problem so I'm limited in what I can do

**Comment by Subbarao6338** [comment]
https://github.com/rebelonion/Dantotsu/assets/76580346/f59f367d-9c53-48bf-ae96-593bcb0008bb

**Comment by rebelonion** [comment]
This should be fixed in the next beta and release

**Comment by Subbarao6338** [comment]
Thanks 🙏
