### ISSUE TITLE
Marking episodes as watched without actually watching it. 

### ISSUE THREAD

**Issue by Ykuzhe** [rebelonion/Dantotsu#108]
Just like the title suggests, I think it would be nice to add a feature that lets you do this. It's nothing big but let's say you watched a series that has a few episodes or so on that isn't Dantotsu (like a website or something) and when you check out the series on Dantotsu in your library it's like marked watched (grayed out) but there's no progression bar under the episodes. That's what this request is for, making it so when you set a series completed or rewatched it also adds that progression bar to the end instead of the episodes being greyed out. This is probably a ton of work already but maybe if you click a series on your library there would be like a "Select All" thing at the top and you could like mark the selected series as watch.

Sorry if this request seems silly haha! Just thought it would be a nice little QoL.

**Comment by rebelonion** [comment]
I might not be understanding you, but you can already mark episodes as watched:
![Screenshot_20231230_025307_Dantotsu.jpg](https://github.com/rebelonion/Dantotsu/assets/87634197/c2aabb81-d6a7-4faa-af05-dc722290cb82)

**Comment by rebelonion** [comment]
The bar is supposed to be your current progress in watching the episode video itself, but I'm open to setting it to 100% if you manually marked complete

**Comment by rebelonion** [comment]
I can't do it automatically because that could screw up people's positions if they're rewatching something. 
And I don't know for sure when I'll get to it because I have a lot I'm working on, but it's added to the list.

**Comment by rebelonion** [comment]
After deliberation and talking it over, we'd rather keep that line specifically for watch time
