### ISSUE TITLE
Why wont other languages be supported?

### ISSUE THREAD

**Issue by Ninbusi** [rebelonion/Dantotsu#11]
It seems extremely possible and easy to do with the way aniyomi extensions are designed. They already have seperate extensions for different languages. The app would still remain in English but the other languages would still be available, right?

**Comment by rebelonion** [comment]
I don't plan on officially supporting supporting other languages, but I do plan on including extension settings.
An example of what I am not going to take time to fix would be if Hebrew/Arabic/some language written right to left doesn't format correctly.

**Comment by rebelonion** [comment]
#10
