### ISSUE TITLE
Make it save preloaded links

### ISSUE THREAD

**Issue by J4zzyB1te7s** [rebelonion/Dantotsu#110]
Is it possible to save preloaded links so next time when you watch something it won't try to load the servers it instantly load the video

**Comment by Zaxx69** [comment]
There is option named "make default" while choosing links ,click on that ,and it will remember the link

**Comment by J4zzyB1te7s** [comment]
> There is option named "make default" while choosing links ,click on that ,and it will remember the link

But it still loads the  servers I'm talking about preloading the links and saving them locally it will save time

**Comment by rebelonion** [comment]
I don't know if it's worth all the dev time to save half a second in loading a video.

Plus many sites use links that expire, so it would cause lots of problems.

**Comment by J4zzyB1te7s** [comment]
> I don't know if it's worth all the dev time to save half a second in loading a video.
> 
> Plus many sites use links that expire, so it would cause lots of problems.

Make it toggleable

**Comment by J4zzyB1te7s** [comment]
> > I don't know if it's worth all the dev time to save half a second in loading a video.
> > Plus many sites use links that expire, so it would cause lots of problems.
> 
> Make it toggleable

Or make it if the links are expired load the links usual way

**Comment by rebelonion** [comment]
> Or make it if the links are expired load the links usual way

Checking would mean an http request, so you lose any quickness you gained

Like I said, it's really not worth the dev time, but if you wanna add it yourself, go ahead
