### ISSUE TITLE
More Android TV Icons/Banners for the skins

### ISSUE THREAD

**Issue by AkiraKusanagi** [rebelonion/Dantotsu#113]
I'll put this stuff here I guess...

**Comment by AkiraKusanagi** [comment]
For now I have Mono and Blue, it'll take a bit because I have to make the icons from the ground up.

**Comment by AkiraKusanagi** [comment]
Icons:
![IMG_20231227_035758~2](https://github.com/rebelonion/Dantotsu/assets/137284132/06ba76ae-70fa-456e-a2ac-031b73b8dcdd)

![IMG_20231227_035758~4](https://github.com/rebelonion/Dantotsu/assets/137284132/1520280b-a81e-4d54-adfc-1136b5dcb121)

**Comment by AkiraKusanagi** [comment]
While I'm adding more, I'll just edit the comment on top.

**Comment by AkiraKusanagi** [comment]
Green
![IMG_20231227_035758~2-1](https://github.com/rebelonion/Dantotsu/assets/137284132/52328adf-7680-4b9d-abb2-87791f5227fb)

**Comment by AkiraKusanagi** [comment]
Purple
![IMG_20231227_035758~2-2](https://github.com/rebelonion/Dantotsu/assets/137284132/57714588-bfef-484d-8fe6-9578eaaa1f99)

**Comment by AkiraKusanagi** [comment]
Red (It's Android's fault, so it's a bit more like pink, but whatever)
![IMG_20231227_035758~2-4](https://github.com/rebelonion/Dantotsu/assets/137284132/9019d7d9-8366-41ce-ac80-7896b1c9b470)

**Comment by AkiraKusanagi** [comment]
Pink
![IMG_20231227_035758~2-5](https://github.com/rebelonion/Dantotsu/assets/137284132/0d4d1a5a-f662-4ad8-85cb-c45b75403319)

**Comment by AkiraKusanagi** [comment]
Pink
![IMG_20231227_035758~2-6](https://github.com/rebelonion/Dantotsu/assets/137284132/2cd65c22-47cb-421a-ae3b-061dd8ff5be9)

**Comment by AkiraKusanagi** [comment]
The OG one I made for Dantotsu
![IMG_20231227_035758](https://github.com/rebelonion/Dantotsu/assets/137284132/653a2948-6378-47d2-b3f4-84166ba618f5)

**Comment by rebelonion** [comment]
🙏
