### ISSUE TITLE
Epsiode is not playing in anime World India.

### ISSUE THREAD

**Issue by Coolboy067** [rebelonion/Dantotsu#114]
Can you please fix it..

When we try to play episode in animeworldindia it show source to play it but we clink on th source and try to play the 
episode it say player error 3003.

Can you please fix this problem.

![Screenshot_20240105-174121](https://github.com/rebelonion/Dantotsu/assets/155737114/dcded51d-07a0-4389-87b8-698b77173045)

**Comment by rebelonion** [comment]
Anime world India has incorporated certain protections that make it hard to correctly obtain the video in dantotsu.

This is a problem that won't be fixed any time soon.

I'd recommend using a different extension.
