### ISSUE TITLE
Adding Support for 3rd Party Extensions

### ISSUE THREAD

**Issue by animeprofiepiture** [rebelonion/Dantotsu#118]
As Tachiyomi has dropped support for all but few extensions, it would be nice to have support for 3rd party ones.

**Comment by InKeaton** [comment]
> Yeah this is planned

Do you have any idea of how much will it take? Sorry for the impatience

**Comment by rebelonion** [comment]
I already have a solution in discord, so hopefully not too long

**Comment by InKeaton** [comment]
> I already have a solution in discord, so hopefully not too long

Thank you for your response :)
