### ISSUE TITLE
Photo is not saving in gallery.

### ISSUE THREAD

**Issue by Coolboy067** [rebelonion/Dantotsu#123]
Plz solve this problem when we try to save anime or anime characters photo.  photo is not saving it only shows save option but it does not work.
![Uploading Screenshot_20240113-172651.jpg…]()

**Comment by rebelonion** [comment]
I need more information than "it does not work" 
If you uploaded an image it broke and doesn't show

**Comment by Coolboy067** [comment]
When i try to save anime cover or some characters photo in gallery it show save option but when i click on that button it doesnot work it only shows the button to save photo but actually it doesn't save.

![Screenshot_20240113-172651](https://github.com/rebelonion/Dantotsu/assets/155737114/3c892cdb-73c8-4a31-86a7-20c0b47b0653)

**Comment by rebelonion** [comment]
Is there an error? Or any message?
The image is saved to the downloads folder, so it might not show in your photos app. Have you checked the downloads folder?

**Comment by Coolboy067** [comment]
No it does not save in download folders or gallery

**Comment by rebelonion** [comment]
Can you answer all my questions please

**Comment by Coolboy067** [comment]
It does not show any message or error when i click on save option.

**Comment by rebelonion** [comment]
What type of device and what android version do you use?
This seems to be a device-specific problem.

**Comment by Coolboy067** [comment]
I use galaxy M01 core and its android version 10.

**Comment by rebelonion** [comment]
I'm not sure this will fix it, but it at least should tell you why it's not saving. you can also press on the popup to copy the message to the clipboard. Feel free to try that if you wish
https://file.io/YtLI3QbuVzi4

**Comment by Coolboy067** [comment]
Above link saying transfer requested has been deleted can you please sent me this link again.

**Comment by rebelonion** [comment]
let's try this link 
https://drive.google.com/file/d/1zjOw986hc4HH_THIMClm7PYUJVTsC5ht/view?usp=sharing

**Comment by Coolboy067** [comment]
Is this the latest version of dantotsu.

**Comment by rebelonion** [comment]
It is the pretest version from the discord which has not been released to GitHub yet

**Comment by Coolboy067** [comment]
Ohh i installed the app from your above given link  then i try to save image and  it say failed to save image so please solve this problem.


![Screenshot_20240114-193731](https://github.com/rebelonion/Dantotsu/assets/155737114/b43a5bfd-2059-4a2f-ac67-4e049d3a7c70)

**Comment by Coolboy067** [comment]
Oh thank you so much jerson2000. It work .
