### ISSUE TITLE
Extensions Bugged

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [rebelonion/Dantotsu#125]
Well i installed the apo and at the laoding of logo when the logo animates and slides i see failed to get manga extensions then i tried installing extensiojs for anime it didnt worked i forced legacy installer then it worked but as i dont have the options to see manga extensions how can i use and download them :?And except this all things are op but because im not able to install manga extensions it remains only as an anime app for me
![Screenshot_2024-01-14-13-14-07-619_ani dantotsu](https://github.com/rebelonion/Dantotsu/assets/112297620/1ff982fe-9467-446c-8c08-5a5d0558597d)

**Comment by rebelonion** [comment]
manga extensions broke recently
I have a fixed version going out to stable and beta within the next few days
if you can't wait, join the discord to get the pretest.

**Comment by ALMIGHTY-VC** [comment]
Thanks for such a quick response well will definitely join your discord :)
