### ISSUE TITLE
Autoskip not working.

### ISSUE THREAD

**Issue by ShankarKSH001** [rebelonion/Dantotsu#127]
I enabled autoskip opening and ending.
But I doesn't working. I also restart the app but it doesn't working.

**Comment by aayush2622** [comment]
![Screenshot_20240114-211953_Dantotsu β](https://github.com/rebelonion/Dantotsu/assets/99584765/698a1bd9-f06a-49b6-b1fc-b35fefbba89f)
Un Toggle this and then if a anime have timestamps it will autoskip

**Comment by ShankarKSH001** [comment]
Sorry I don't understand, you means turn off those three option?

**Comment by aayush2622** [comment]
Proxy

**Comment by Shebyyy** [comment]
@ShankarKSH001 
Try turn off "use proxy for timestamps"

**Comment by ShankarKSH001** [comment]
Now it's working. Thanks for yours replies bros.
