### ISSUE TITLE
Dub contents not showing.

### ISSUE THREAD

**Issue by ShankarKSH001** [rebelonion/Dantotsu#128]
In many extentions dub contents not showing.
For example GOGOANIME has both sub and dub contents, but only sub contents are showing.

**Comment by rebelonion** [comment]
![image-3](https://github.com/rebelonion/Dantotsu/assets/87634197/99600221-311a-4a1c-b46a-f2f47f1e1f32)
![image-4](https://github.com/rebelonion/Dantotsu/assets/87634197/88efaca6-1c66-458a-8cab-2e5d54d466a6)
![image-5](https://github.com/rebelonion/Dantotsu/assets/87634197/bea25d15-1ba7-4d74-b249-aad535dcca27)
