### ISSUE TITLE
Do you plan to implement light novels? If so how?

### ISSUE THREAD

**Issue by Ninbusi** [rebelonion/Dantotsu#13]
I have searched almost everywhere and could not find any app that had sources for light novels as seperate extensions. Are there other people working on this project to make Ln extensions or is it just you? How are you planning to implement light novels is my question.

**Comment by rebelonion** [comment]
It is planned. I'm not going to go into how until it becomes for definite.

**Comment by rebelonion** [comment]
Added in v2.0.0
