### ISSUE TITLE
Failed to get manga extensions

### ISSUE THREAD

**Issue by Zkewap31** [rebelonion/Dantotsu#131]
![Screenshot_20240115-054133](https://github.com/rebelonion/Dantotsu/assets/143828058/448c134a-01ec-4c31-9a46-6e8db12d8ae8)

**Comment by rebelonion** [comment]
manga extensions broke recently
I have a fixed version going out to stable and beta within the next few days
if you can't wait, join the discord to get the pretest.

**Comment by Zkewap31** [comment]
it's okay I'll wait thanks❤️
