### ISSUE TITLE
Animepahe can't find titles

### ISSUE THREAD

**Issue by Ravenora** [rebelonion/Dantotsu#136]
Any other source works perfectly but animepahe can't find title.
I tapped on the "Wrong Title?" and typed in the English version of the name, either way yields no results. 
Dantotsu Version 2.0
Tried all 3 domains of animepahe, none of them worked.
![Screenshot_20240116-180552_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/76664407/f9701e1c-a4ec-43c8-b8f7-c1ee687636de)

**Comment by JinDevil21** [comment]
yeah cause  website got some ddos guard human verification like cloudflare you need to wait or try other extensions
