### ISSUE TITLE
remove rotate button from exoplayer 

### ISSUE THREAD

**Issue by Yutatsu1** [rebelonion/Dantotsu#137]
now that we have auto rotate can you remove this 
![Screenshot_2024-01-17-23-18-39-07](https://github.com/rebelonion/Dantotsu/assets/126276749/6697240a-6585-4642-b9d2-89cccec199e1)

**Comment by rebelonion** [comment]
it doesn't always rotate though.
I can look into adding a button to hide it.

**Comment by Yutatsu0** [comment]
> it doesn't always rotate though. I can look into adding a button to hide it.

thanks
