### ISSUE TITLE
Separate NSFW and normal extension

### ISSUE THREAD

**Issue by Aeropro4** [rebelonion/Dantotsu#141]
Just a request to separate the adult extensions and normal extensions as while opening a normal anime it shows NSFW extensions as well which is of no use and in the adult section it shows normal extensions as well.

**Comment by aayush2622** [comment]
toggle nsfw extension in settings

**Comment by Aeropro4** [comment]
> toggle nsfw extension in settings
> 

Yeah done but then also
![Screenshot_20240119_122414_Dantotsu .jpg](https://github.com/rebelonion/Dantotsu/assets/113044496/e1953a93-e1e1-4735-8a7b-0c6f1d8d92df)

![Screenshot_20240119_122431_Dantotsu .jpg](https://github.com/rebelonion/Dantotsu/assets/113044496/fbc27f73-7e08-420a-be69-644b3172c0a6)

**Comment by aayush2622** [comment]
some non NSFW sources are also marked as nsfw so you wont see then too

**Comment by Aeropro4** [comment]
> some non NSFW sources are also marked as nsfw so you wont see them too

Uhh sorry to say but I don't think u are understanding the message I wanna say
The thing I wanna say is this👇

These are screenshots of sources of saikou

This screenshot is of normal anime.
![Screenshot_20240119_123703_Saikou .jpg](https://github.com/rebelonion/Dantotsu/assets/113044496/a8685403-d6f9-47c4-a6b1-d4c054b3dace)


And this of some adult anime.
![Screenshot_20240119_123751_Saikou .jpg](https://github.com/rebelonion/Dantotsu/assets/113044496/fa1eef82-9847-4ac6-95a1-ee2e4eb2b101)

So wanna say is to hide the adult sources from normal anime and as for those who are marked NSFW. well np 
Sry again for this large message

**Comment by aayush2622** [comment]
dantotsu uses aniyomi extensions they marked some extensions as nsfw  which are not (mangadex) so if we hide NSFW extension you wont see (mangadex) in non NSFW list

**Comment by Aeropro4** [comment]
> dantotsu uses aniyomi extensions they marked some extensions as nsfw  which are not (mangadex) so if we hide NSFW extension you wont see (mangadex) in non NSFW list

Oh k thanks
