### ISSUE TITLE
Login only with myanimelist

### ISSUE THREAD

**Issue by MakuSensei** [rebelonion/Dantotsu#144]
Hello. First I only use myanimelist to manage my entire list of animes and mangas. Why can't I just use myanimelist? If I don't want to create an account on anilist

**Comment by rebelonion** [comment]
Because this app is focused on data from anilist.

**Comment by MakuSensei** [comment]
> Because this app is focused on data from anilist. 

Hello, if I create an anilist account, will it not affect my status in myanimelist?

**Comment by MakuSensei** [comment]
> Because this app is focused on data from anilist. 

Hello, if I create an anilist account, will it not affect my status in myanimelist?

**Comment by Shebyyy** [comment]
> > Because this app is focused on data from anilist. 
> 
> Hello, if I create an anilist account, will it not affect my status in myanimelist?

It will, first login with anilist
And go to settings < account < Login on myanimelist
It will update progress in both anilist and myanimelist
