### ISSUE TITLE
[FEATURE REQUEST] Recently updated from your list section.

### ISSUE THREAD

**Issue by Taimoor-Tariq** [rebelonion/Dantotsu#147]
Would love to see a new section which shows the recently released stuff from your lists.

Maybe even a filter on the Recently updated section on the Anime/Manga pages that lets u filter "list only"

**Comment by Shebyyy** [comment]
You can enable this option

![IMG-20240120-WA0013.jpg](https://github.com/rebelonion/Dantotsu/assets/83452219/30075220-897b-4e93-aa0d-c3fb468904d9)
