### ISSUE TITLE
Add Local Storage

### ISSUE THREAD

**Issue by SinchanBanerjee-tech** [rebelonion/Dantotsu#148]
Exactly as it sounds. How about adding a storage for our own stuff? A local file! Like Aniyomi.
![Screenshot_20240121_141136_Aniyomi](https://github.com/rebelonion/Dantotsu/assets/84694749/654a2f3d-19b6-47d1-ab4b-993dd1c78a92)
![Screenshot_20240121_141145_Aniyomi](https://github.com/rebelonion/Dantotsu/assets/84694749/567b58b3-4dcf-4a09-abda-657ec1a1f590)

**Comment by rebelonion** [comment]
that's what "Downloaded" is
