### ISSUE TITLE
Cast making phone unusable 

### ISSUE THREAD

**Issue by KostaGorod** [rebelonion/Dantotsu#157]
After update, looks like there's been changes to the the  Cast feature. 

After casting starts my phone is unresponsive, showing black screen and not responsive to navigation gestures (swiping from edges, no buttons).
Also Google assistant saying my phone is locked but only black screen is shown (additionally to the Google assistant).

I don't like the old 3rd party app dependency for casting, but at least providing the option in the settings would be nice

**Comment by aayush2622** [comment]
Long press cast button to use external app

**Comment by rebelonion** [comment]
long pressing the casting button uses the old method, as stated in the update patchnotes

**Comment by rebelonion** [comment]
I'd also appreciate more info in your issue

**Comment by KostaGorod** [comment]
I was about to comment I found this information in the change log,
Thanks for the quick response and the great work!

**Comment by KostaGorod** [comment]
> I'd also appreciate more info in your issue

I'll record my screen with touch operations  on,
Let me know what else I can get

OnePlus 8 - IN2013
OxygenOS 11.0.9.9-IN21AA
Android 11

**Comment by aayush2622** [comment]
Long press cast button to use external app

**Comment by aayush2622** [comment]
Tf when did I send that msg

**Comment by Ghostscare** [comment]
I have the samen issue on a oneplus 7. Moment you start casting with native app. My screen goes black and Starts showing my lock screen with intervals of a few seconds. Can't unlock the phone and have to restart it.

**Comment by rebelonion** [comment]
> I have the samen issue on a oneplus 7. Moment you start casting with native app. My screen goes black and Starts showing my lock screen with intervals of a few seconds. Can't unlock the phone and have to restart it. 

It might be a OnePlus related issue then. A video would be appreciated

@KostaGorod 
@Ghostscare

**Comment by Ghostscare** [comment]
@rebelonion 
How do i send a video? I always get a size error when trying to put it here.

**Comment by aayush2622** [comment]
join discord or telegram
