### ISSUE TITLE
Offline mode exit 

### ISSUE THREAD

**Issue by Spidergoku9001** [rebelonion/Dantotsu#161]
I accidentally turned offline mode on how do I exit it?? 
![Screenshot_2024-01-26-15-18-31-766_ani dantotsu](https://github.com/rebelonion/Dantotsu/assets/85983159/0efa0db0-6660-4904-be3d-ec33e200e2fa)

**Comment by Shebyyy** [comment]
Go to anime or manga page click on settings icon
You can turn off from there.
