### ISSUE TITLE
A single anime does not work with several sources, although these sites have all episodes.

### ISSUE THREAD

**Issue by Kodionpi** [rebelonion/Dantotsu#167]
A single anime does not work with some sources, although the respective source/site has all episodes.

meitantei conan/Case Closed shows 26 episodes of another anime under Aniwatch as source. Nothing is displayed under animepahe either. 

Both sides have all the episodes and work well with other anime too.

**Comment by Shebyyy** [comment]
Use wrong title option and select correct title.
 it will show all episodes.

**Comment by Kodionpi** [comment]
I see. I overlooked that option. Thank you! At first I thought it was the right title because it showed the appropriate number of episodes.
