### ISSUE TITLE
Player error 2000 (error_code_io_unspecified) source error

### ISSUE THREAD

**Issue by AdilSun** [rebelonion/Dantotsu#170]
This error shows up to all sources
![IMG_20240201_102648](https://github.com/rebelonion/Dantotsu/assets/47750924/e2bfa261-46c1-45ce-9dc5-8a2a42ce6dbd)

**Comment by rebelonion** [comment]
All sources in all extensions?

**Comment by AdilSun** [comment]
Yes

**Comment by AdilSun** [comment]
> All sources in all extensions?

Yes

**Comment by rebelonion** [comment]
This is either a device specific problem or a network issue on your end. Try the DNS setting in app or a vpn
