### ISSUE TITLE
Says it crashes due to webview

### ISSUE THREAD

**Issue by Toiletmason** [rebelonion/Dantotsu#172]
If I spam opening the app eventually I get past the crashing.

**Comment by Toiletmason** [comment]
@aayush2622 

It's up to date. 
![Screenshot_20240204_162205_Settings.jpg](https://github.com/rebelonion/Dantotsu/assets/23698116/b9e73e99-e834-4af4-ba7b-4eb440b1b6fe)

**Comment by rebelonion** [comment]
can you be a little less vague than "Says it crashes due to webview"

**Comment by Toiletmason** [comment]
https://github.com/rebelonion/Dantotsu/assets/23698116/55ed03d1-897c-49fb-a81b-0dfd8f935f70

I've updated to 2.1.0 and now it doesn't open at all. @rebelonion

**Comment by rebelonion** [comment]
@aayush2622 is this the problem where someone had a weird version of webview?

**Comment by aayush2622** [comment]
it can be

**Comment by rebelonion** [comment]
> it can be

How was it fixed?

**Comment by rebelonion** [comment]
@Toiletmason try uninstalling and reinstalling webview

**Comment by Toiletmason** [comment]
@rebelonion When I uninstall updates then it works normal, as soon as I update, it's broken again.

I should have prefaced this that this has always happened since I found your app before the 2.0 release. It was never an issue with Saikou.

**Comment by rebelonion** [comment]
Are you updating through the Google Play store?

**Comment by Toiletmason** [comment]
@rebelonion yes.![ResizedImage_2024-02-09_23-44-31_2154.jpg](https://github.com/rebelonion/Dantotsu/assets/23698116/e1627e16-a914-42e0-a0bd-f5da6fa3f921)

**Comment by brahmkshatriya** [comment]
Might be better if you provided some crash log, Google getting crash log of an app
