### ISSUE TITLE
Casting is unstable

### ISSUE THREAD

**Issue by JohnVictoryz** [rebelonion/Dantotsu#176]
Today or basically yesterday as it's midnight at the time of writing i was trying to watch a movie that i had been casting to my main TV and when i started watching it after 10 to 15 minutes it stoped and started from the begging i thought it just lagged out so i seeked it to the time it had been and continued watching after another 10 to 15 minutes same thing it jumped to the begging now i was frustrated i thought that because i had the phone on idle maybe android stoped dantotsu from operating due to battery optimization settings so i went to [dont kill my app](https://dontkillmyapp.com) and did all the things to stop any attempts of android stoping dantotsu from working i resumed it thinking this will surely be the end and this would fix it oh boy i was wrong after again 10 to 15 minutes the same thing happened it jumped to the begging i just shook it off annoyed and resumed it then it happened again after how much time guess 10 to 15 minutes now i am really confused but to my surprise when i tried to resume it it suddenly stoped casting to my tv so basically dantotsu has stoped casting but my tv started going on it's on without me controlling it through dantotsu i dont know what went wrong but after i exited from the cast using my remote it continued playing on the background for no reason and it was not available to connect to it using chromecast i restarted the tv but i was so furious that i just sprinted to my computer to write this issue on github i know some things about android apps since i had gotten around to programming some and even played with chromecast before this thing never had happened to me neither in the progress of programming my app nor when using an other chromecast app. now i am gonna list some details that might be needed to understand what happened:

Phone: Samsung Galaxy A72 4G
One UI Version: 5.1
Android Version: 13
Security Patch level:  September 1, 2023
App: Dantotsu β(Dantotsu beta)
Dantotsu version: 2.1.0-beta01

P.S also i like the way you have named the beta version of the app because you took the β from the greek alphabet which is pronounced beta in english and used it to indicate that this is the beta version this comes close to my since i am greek anyways all in all i like the name you chose for the beta version if you want me to sent you anything dont hesitate to contact me either through here or by sending my a message on discord: tutelwastaken(i am also in the server) or using email: john.g.zioupos@protonmail.com 
**That's all**

**Comment by rebelonion** [comment]
The "new" way of casting in app has been reported to cause problems for some people (see #157). You can use the old method by long pressing the cast button

**Comment by JohnVictoryz** [comment]
> The "new" way of casting in app has been reported to cause problems for some people (see #157). You can use the old method by long pressing the cast button

thx also are there any docs on how to start developing with dantotsu @rebelonion like how to import this on android studio etc. cause i want to help.

**Comment by rebelonion** [comment]
no docs specific to dantotsu, but it's pretty statndard
- fork project
- pull to local machine (Github Desktop makes that easy)
- open with android studio

If you have questions or need help, the best way to reach me would be in the discord server

**Comment by rebelonion** [comment]
I switched the default beck to external and labeled the internal as experimental, as it seems to be picky on what phones work well
