### ISSUE TITLE
Download button which show up in server options for external download managers not showing.

### ISSUE THREAD

**Issue by athish0** [rebelonion/Dantotsu#177]
I use 1DM to download. I used to do so using the download button that was available when selecting the servers available, but can't find it after the recent update. Is it a bug? 
![Screenshot_2024-02-04-10-45-55-620_ani dantotsu](https://github.com/rebelonion/Dantotsu/assets/87030018/94fc4ec5-0dca-4232-8177-560544635205)

**Comment by rebelonion** [comment]
![image](https://github.com/rebelonion/Dantotsu/assets/87634197/0f8a33f5-2805-499e-8b7b-9f32b4bd7d56)

long press the download button to use a download manager
