### ISSUE TITLE
status should not auto update backwards

### ISSUE THREAD

**Issue by WeepingClown13** [rebelonion/Dantotsu#18]
Currently if an episode earlier than what the status says is finished, auto update reupdates the status to the number of that episode, ie it could auto update to 5 from 10. This is not ideal for most cases, especially when you've to revisit an old episode. So backward updates should only be possible in case of manual updates and auto updates should ideally stay the latest episode number among the two.

**Comment by rebelonion** [comment]
fixed in [v0.1.5](https://github.com/rebelonion/Dantotsu/releases/tag/v0.1.5)
