### ISSUE TITLE
Saving Manga Pages Not Working (Edit: and some pages are often messed up when long pressed)

### ISSUE THREAD

**Issue by Sickhead01** [rebelonion/Dantotsu#189]
When I long press a page and hit the save button nothing happens in both 2.2.0-beta02 and stable. The share and reload buttons work though.

**Comment by rebelonion** [comment]
thanks for the issue.
any errors or popups, or just nothing happens

**Comment by Sickhead01** [comment]
No popups or anything. Just nothing happens

Also i've noticed since since version 2.1.0 stable and beta many times when i long press a page it appears messed up and gets saved that way as seen here:

![Screenshot_20240209-001644](https://github.com/rebelonion/Dantotsu/assets/70452344/2dd8679d-628a-42c8-9b36-b15fe5c24222)

**Comment by rebelonion** [comment]
> Also i've noticed since version 2.1.0 stable and beta many times when i long press a page it appears messed up and gets saved that way as seen here:

that's actually source dependent. some sources scramble their images to prevent you from just downloading them
so it's always been a thing

**Comment by Sickhead01** [comment]
But the image looks normal when i'm reading the chapter. Like this:
![Screenshot_20240209-004756](https://github.com/rebelonion/Dantotsu/assets/70452344/25391b3f-666c-406e-89c5-303805ec6a2b)
This is from the same source of the first image. It's only when i long press the image preview becomes scrambled. That's still the source's doing?

**Comment by rebelonion** [comment]
> But the image looks normal when i'm reading the chapter. Like this: This is from the same source of the first image. It's only when i long press the image preview becomes scrambled. That's still the source's doing?

that's because the extension does the unscrambling on the fly. when you download, the app just passes the original file link to the downloader.

**Comment by Sickhead01** [comment]
Ah ok. I just tried another source (mangadex) and it's not scrambled when i long press. The save button still doesn't work though

**Comment by rebelonion** [comment]
this is fixed in alpha, will be pushed in the next beta/release
