### ISSUE TITLE
Episode doesn't opening

### ISSUE THREAD

**Issue by Samrat0000** [rebelonion/Dantotsu#19]
Can you please fix it.
In some extention like animesaga , animeworld india. Anime are found but doesn't  open episode and doesn't show any source to watch anime episode.
/
![Screenshot_20231026-190537](https://github.com/rebelonion/Dantotsu/assets/148989926/618fcb7f-8033-444c-8778-2a7b39f7e1c5)

Please fix it..

**Comment by rebelonion** [comment]
Will be fixed in the next update
