### ISSUE TITLE
always continue shows not working in the latest update 

### ISSUE THREAD

**Issue by Kawsar18** [rebelonion/Dantotsu#190]
always continue shows not working in the latest update it doesn't select the episode automatically anymore

https://github.com/rebelonion/Dantotsu/assets/126276749/3c576fa5-1447-46b2-9564-7eff4ca313df

**Comment by ShankarKSH001** [comment]
> always continue shows not working in the latest update it doesn't select the episode automatically anymore
> 
>  Record_2024-02-09-17-57-00.mp4

Try this maybe it's work,
Go to settings>common
turn off & again on always continue shows & restart

**Comment by ShankarKSH001** [comment]
Yes it's not working like before update

**Comment by rebelonion** [comment]
Should be fixed next update
