### ISSUE TITLE
Always getting "Couln't find anything x( Try another source"

### ISSUE THREAD

**Issue by WeepingClown13** [rebelonion/Dantotsu#192]
Opening any anime, with any source, always gives this same error. It does not find any anime at all. I tried this with vpn connections as well as different DNS (from inside the app as well as externally), and it always show the same. This issue has been persisting for a while now and it renders the whole app useless for watching anime.

**Comment by rebelonion** [comment]
I don't know what to tell you. This is entirely something to do with your Internet/extension choices. Not much we can do about that.

**Comment by WeepingClown13** [comment]
@rebelonion it used to work simply fine with the same internet provider, and it is not like changing providers is giving any different result. And the extensions I use are simply animepahe and myanime, which are normally available for me when I visit the websites. If you don't want to address it as an issue, that is fine by me, but closing it without even asking for any further info is simply disheartening as someone who's been an active user of Dantotsu since it came to be.

**Comment by rebelonion** [comment]
You saying 'with any source' makes this inherently not an 'issue' with the app, but some sort of network issue. If you have actually only tried 2 sources, that's completely different, but still most likely a network issue. I reserve GitHub issues for actual bugs. If you want help with that sort of problem, the best place is telegram or discord.
That being said,
Have you tried opening in webview?
Are there extension updates?
Have you tried using a dns?

**Comment by WeepingClown13** [comment]
I do not mean to say that you should treat this as a bug itself. But for future clarity, you could have mentioned the things about telegram or discord in the message that you left before closing the bug, which also would have made sense. I don't take your work for granted, and I certainly appreciate it a lot, and that is exactly why I want the communication to be smoother. Also keep in mind that not everyone uses telegram or discord.

And finally, opening once in webview seems to be making the episodes available in the app the next time onwards (which fixes my problem and thanks for that) and that surely does not sound like a network issue to me. The fact that across different providers, networks and dns the episodes were unavailable in the app regardless of it being available in any browser does not point to a network issue either. I had the extensions up-to-date as well. So if you want to treat it as a network issue on my end, that is totally fine by me and I appreciate that you replied, but this \*may* be something other than that as well.

**Comment by rebelonion** [comment]
> opening once in webview

this is because of cloudflare or some other type of ddos protection
