### ISSUE TITLE
is there a way to create an offline list

### ISSUE THREAD

**Issue by JunkyardCat** [rebelonion/Dantotsu#197]
like list of favorite anime and episode
without creating an my ani list

if this cant be done may i know the reason as to why not?

**Comment by rebelonion** [comment]
The only way is downloading and using offline mode

**Comment by rebelonion** [comment]
I mean downloading the anime and manga to your device

**Comment by JunkyardCat** [comment]
will there be plans to incorporate an offline favorite?

**Comment by rebelonion** [comment]
Probably not. The most I'd do is something like a reordering of downloads.
