### ISSUE TITLE
Resume auto continue feature 

### ISSUE THREAD

**Issue by Aeropro4** [rebelonion/Dantotsu#2]
Please add the auto continue to feature in which when we watch an anime episode one time and when we open the anime a second time it auto plays where we left the episode which was in the old saikou.

**Comment by rebelonion** [comment]
I'll take a look 👍

**Comment by Aeropro4** [comment]
> I'll take a look 👍

Thx pls do

**Comment by Aeropro4** [comment]
Tbh this app need very much polishing to be on a par with saikou

**Comment by rebelonion** [comment]
Well yes did you not notice the giant ALPHA warning?

**Comment by Aeropro4** [comment]
> Well yes did you not notice the giant ALPHA warning? 

Lol yeah sry

**Comment by Aeropro4** [comment]
Its fixed thx
