### ISSUE TITLE
Storage Path Directory 

### ISSUE THREAD

**Issue by AriaZen0kis** [rebelonion/Dantotsu#203]
![Screenshot_20240221-225658](https://github.com/rebelonion/Dantotsu/assets/111241602/d6aec904-24a7-4bff-aa01-cdbe6d0a746f)

To be able to choose download location for either the SD Card or Phone Storage.
That setting right there doesn't work ?

**Comment by rebelonion** [comment]
duplicate of #180

**Comment by KaguyaUchiha** [comment]
Same issue ;-;
