### ISSUE TITLE
Card glitching when download is in progress 

### ISSUE THREAD

**Issue by GitGitu79** [rebelonion/Dantotsu#210]
Happen when downloading a novel, don't know if it happens anywhere else

https://github.com/rebelonion/Dantotsu/assets/152173286/e4927583-fa70-4cd8-9393-9dae2ace0f2e

**Comment by rebelonion** [comment]
it's sort of on purpose

**Comment by sneazy-ibo** [comment]
it even looks great if you download stuff on compact mode
