### ISSUE TITLE
Clickable Source ✨🙏🏻

### ISSUE THREAD

**Issue by SinchanBanerjee-tech** [rebelonion/Dantotsu#214]
Instead of putting the source in 'Relations', can you please make clickable source in info section? Like for example, Studio Madhouse is clickable below it.

Or maybe you can keep both :D

![Screenshot_20240303_083955_Dantotsu ](https://github.com/rebelonion/Dantotsu/assets/84694749/38ff3f56-34e0-405b-8d71-55c20a671f9e)
![Screenshot_20240303_084111_Dantotsu ](https://github.com/rebelonion/Dantotsu/assets/84694749/7ab9eeb4-faa7-4c8f-a466-9b6b15001f57)

**Comment by rebelonion** [comment]
don't open an issue in 2 places at once
