### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Aruraka** [rebelonion/Dantotsu#215]
Can u guys please add a section for asian dramas like korean nd chinese too nd make the downloaded videos available in the app itself instead of in the internal memory of phone please? Thanks I would like to hear from u guys

**Comment by rebelonion** [comment]
is asian dramas a section on anilist?

**Comment by Aruraka** [comment]
I don't know thats why I'm asking for this feature

**Comment by Neonfix07** [comment]
Dantotsu is an Anilist only client so u better drop your request 😕

**Comment by rebelonion** [comment]
> I don't know thats why I'm asking for this feature

It does not appear to have them.
