### ISSUE TITLE
App restarts when clicking on profile and selecting stats

### ISSUE THREAD

**Issue by itsmechinmoy** [rebelonion/Dantotsu#216]
Version: Alpha-Build: 2.2.0+93fa298

Description:
Upon clicking on the profile and selecting stats, the application abruptly restarts. This behavior occurs consistently.

Steps to Reproduce:
1. Open the Dantotsu app.
2. Click on the profile icon.
3. Select the stats option.

Expected Behavior:
The app should display the user's stats without restarting.

https://github.com/rebelonion/Dantotsu/assets/95120262/1340e603-f4e4-4edf-89da-b344348044ad

**Comment by rebelonion** [comment]
fixed
