### ISSUE TITLE
Gogoanime not working

### ISSUE THREAD

**Issue by athish0** [rebelonion/Dantotsu#219]
It's been like this for few days, anime name shows up in the search bar. But not showing here
![Screenshot_2024-03-05-21-41-07-191_ani dantotsu](https://github.com/rebelonion/Dantotsu/assets/87030018/b878967b-3add-454f-bbb3-2e89fe4d1659)

**Comment by Shebyyy** [comment]
Update extension

**Comment by athish0** [comment]
Oh, thanks. I tried uninstalling and reinstalling it, but it didn't work, so I thought it wasn't the problem. It's working now👌
