### ISSUE TITLE
Missing Hospitality of the Hero manga

### ISSUE THREAD

**Issue by JellyCreeperOfficial** [rebelonion/Dantotsu#229]
I am searching for hospitality of the hero manga and have mangadex extension installed. I can find it in just fine in tachiyomi but I am having trouble importing my reading list considering your manga search is not returning me this manga.

**Comment by rebelonion** [comment]
I cannot find that manga on mangadex, myanimelist, or anilist

**Comment by rebelonion** [comment]
if it's 18+, you need to enable adult content on anilist and check the adult box when searching

**Comment by JellyCreeperOfficial** [comment]
> if it's 18+, you need to enable adult content on anilist and check the adult box when searching

Oh didnt realise it was 18+ thank you.
