### ISSUE TITLE
App navigation bar "loses" current item

### ISSUE THREAD

**Issue by AbandonedCart** [rebelonion/Dantotsu#243]
How to reproduce:

Select the manga tab
Select any item
Furiously click back to exit the app
Apologetically open the app again
Manga tab is selected, home is shown
Click home icon
Observe nothing happening
Click manga and watch it work again

Rinse and repeat with anime

**Comment by rebelonion** [comment]
Hmm. I couldn't get it to happen on my device. Any chance of a video?

**Comment by AbandonedCart** [comment]
I checked another device and it looks like it's only happening on the one. Strange.

**Comment by AbandonedCart** [comment]
Setting a default tab seems to fix it. I wonder if it's that it's trying to navigate to the tab that's already shown, so it skips doing anything.

**Comment by AbandonedCart** [comment]
In testing that, I also noticed the continue reading doesn't add items until the first chapter is complete.

**Comment by rebelonion** [comment]
#244
