### ISSUE TITLE
Android 5 support 

### ISSUE THREAD

**Issue by Shiki551** [rebelonion/Dantotsu#246]
I remember i used saikou on android 5 and it worked better why this one requires 6 or higher

**Comment by AbandonedCart** [comment]
I can't speak for the developers of this app, but Google and Android have pushed developers to abandon older versions by raising the minimum on their libraries.

**Comment by Shiki551** [comment]
> Google



> I can't speak for the developers of this app, but Google and Android have pushed developers to abandon older versions by raising the minimum on their libraries.

I understand but i asked bcs i have a old tab and i watch all the anime there and i liked this this app so far but unfortunately i cant get it

**Comment by AbandonedCart** [comment]
Trust me, I get it. My user base had a breakdown when I had to abandon Android 4 in 2023.

**Comment by AbandonedCart** [comment]
Oddly, after running a build with the api warnings upgraded to errors, nothing came back. I think you could build it for 5 without any changes.

**Comment by Shiki551** [comment]
> Oddly, after running a build with the api warnings upgraded to errors, nothing came back. I think you could build it for 5 without any changes.

I tried with apk editor just for curiosity i was able to install it but it crashes when opening the app

**Comment by AbandonedCart** [comment]
I am partially responsible, ironically. I used the API 23 color references because that was the minimum. Fixing those and adding an API 21 network check seems to have gotten it booting up and most of it seems to work. It still needs a lot more testing before it can translate into a PR, though.

**Comment by Shiki551** [comment]
> I am partially responsible, ironically. I used the API 23 color references because that was the minimum. Fixing those and adding an API 21 network check seems to have gotten it booting up and most of it seems to work. It still needs a lot more testing before it can translate into a merge ready PR, though.

So basically you saying that it could work if everything checks right?

**Comment by AbandonedCart** [comment]
It should, at least as long as all the libraries keep supporting it.

**Comment by AbandonedCart** [comment]
The biggest roadblock you are going to hit is video format. Older devices can't decode some of the newer formats.

**Comment by Shiki551** [comment]
> The biggest roadblock you are going to hit is video format. Older devices can't decode some of the newer formats


if it works like saikou it's okay for me

**Comment by AbandonedCart** [comment]
I don't really know how that one worked. I hadn't even heard of tachiyomi until about a week ago.

**Comment by rebelonion** [comment]
It should be fine

**Comment by Shiki551** [comment]
tachiyomi another app i wanted try before but like this one doesn't support android 5

**Comment by rebelonion** [comment]
Should be supported in the next update, thanks to @AbandonedCart in #257
I'll just say now I'm making no promises for how long it will be supported.

**Comment by AbandonedCart** [comment]
It doesn't work in the emulator. There are theme issues, videos don't play, and downloads break if the file names contain special characters (ie. Demon Slayer)

**Comment by rebelonion** [comment]
the video player is mostly unchanged from saikou, so unless exoplayer dropped support, that's surprising.

**Comment by AbandonedCart** [comment]
It didn't drop support, but the videos improved.

**Comment by rebelonion** [comment]
@Shiki551 if you wanna mess around with a build to see what works and what doesn't, here's one:
https://file.io/UV0VpTHzFyHQ

**Comment by rebelonion** [comment]
> It didn't drop support, but the videos improved.

looks like H.264 AVC Main Profile (MP) requires Android 6.0+
which lines up with the error I was getting (format_supported=NO_EXCEEDS_CAPABILITIES).

**Comment by AbandonedCart** [comment]
Forcing it won't work, either.

**Comment by Shiki551** [comment]
it works but if i login on anilist the app crashes and won't open

**Comment by AbandonedCart** [comment]
I didn't get that far into the testing before it was merged.

**Comment by Shiki551** [comment]
It's okay other than that app works great

**Comment by AbandonedCart** [comment]
![Screenshot_20240318_090442](https://github.com/rebelonion/Dantotsu/assets/1173913/68ec1888-f440-46f3-b5c3-03925075ea9e)

Not overly fond of this, though

**Comment by Shiki551** [comment]
It only needs now the anilist to access my anime library

**Comment by AbandonedCart** [comment]
https://github.com/rebelonion/Dantotsu/pull/258/commits/2c3b3b82a70952b1744013c82ab194172c2cff94 fixes login, but you shouldn't have to log in again once that's included. The issue was the automatic scrolling of the page.

**Comment by Shiki551** [comment]
Why would login aggain if i did it once it should be good

**Comment by AbandonedCart** [comment]
You won't need to, since the crash was after login finished.

**Comment by AbandonedCart** [comment]
It will work with AniList. The whole app depends on AniList.

**Comment by Shiki551** [comment]
thnx so much both developers for helping me the app works great now i didn't know i had to update the app to work till now much appreciated
