### ISSUE TITLE
interesting 🐬💎

### ISSUE THREAD

**Issue by Alex178190282** [rebelonion/Dantotsu#262]
add an option where when you enter an anime or manga to choose an extension, from the options of scanning the extensions to find that content with the greatest number of episodes or in the highest quality:) and in the language you prefer let's go bro That will most likely make the app slower but it is a gem

**Comment by AbandonedCart** [comment]
You'd have to install then to determine the contents...

**Comment by Alex178190282** [comment]
> You'd have to install then to determine the contents...

What exactly are you talking about if the extensions are installed from Aniyomi or at least that's how I have them?

**Comment by AbandonedCart** [comment]
> What exactly are you talking about

I'm so happy you asked. I am talking about it being a somewhat silly idea to search all of the extensions you already have to find that out when selecting an item already tells you if the extension has the series. You could go a step further and try to find an extension with the best quality for that video, but then what happens when extensions label all of their videos as 720p and play them at 1080? Do you just never find out? The only real use for the concept would be to tell you what extensions have the content you are trying to find, but then you have to have the extension already.

**Comment by Alex178190282** [comment]
> extension

So if you are very right, it is better to do it as you say, thanks for the comment

**Comment by AbandonedCart** [comment]
I wrote a feature to automatically continue down a source list until the selected show was found, but it requires that you put your extensions in the order you want to search them. As is, you can't actually get the quality of a video until it is selected, so it can't sort them by that. It only does the search from the top down to prevent an infinite loop. It's not quite what you were asking, but it's something.

**Comment by sneazy-ibo** [comment]
What do you think about letting the source search also use the first two synonyms of the media after nothing gets returned since those names are often the mostly used ones especially in the manga community and lead to correct search results in many cases

**Comment by AbandonedCart** [comment]
Are you talking about how the title gets translated?

**Comment by Alex178190282** [comment]
> Are you talking about how the title gets translated?

Yes, the truth is it is a bit complicated to find the correct name of a manga that I have read before to return to it in this app

**Comment by AbandonedCart** [comment]
I was asking @sneazy-ibo if it was title synonyms

**Comment by rebelonion** [comment]
#277 has a better description

**Comment by sneazy-ibo** [comment]
> I was asking @sneazy-ibo if it was title synonyms

Yes the synonyms are also translations of the titles but the first two are mostly alternative titles for it in english which are popular.

**Comment by AbandonedCart** [comment]
That was what I thought you meant, but I wanted to be sure.
