### ISSUE TITLE
Sort/filter by unread/unwatched

### ISSUE THREAD

**Issue by BrunoPascoa76** [rebelonion/Dantotsu#263]
Problem: if you get a lot of updates at once or are just starting a series, you can forget what you have and haven't watched.
Solution: either sorting by number od unread chapters or filtering by it (for example, the "continue reading" may only show entries with unread chapters)
Additional suggestion: having an unread count on the list like how Tachiyomi does it would also be cool

**Comment by rebelonion** [comment]
Anilist does not provide that data sadly.
