### ISSUE TITLE
correction of the previous proposal :vvv

### ISSUE THREAD

**Issue by Alex178190282** [rebelonion/Dantotsu#266]
and they say yes, it is better to simply add the small section that when we are going to choose an extension to watch our anime or manga, we should preferably present the amount of content it has and the quality of the manga or anime, regardless of the name. It's in another language as long as it's the same :33!?

**Comment by rebelonion** [comment]
Showing the quality of every extension would require querying every extension, and that's not something that should be done. You can see what qualities an individual extension has before watching a video.
