### ISSUE TITLE
Library Not Updating 

### ISSUE THREAD

**Issue by deneshwarbhandarkar** [rebelonion/Dantotsu#267]
After new release, manga and anime library is not updating. 
New Anilist features are good but after this update unable to get new anime episodes and new manga chapters

**Comment by rebelonion** [comment]
Could you be more specific with what's not working?

**Comment by deneshwarbhandarkar** [comment]
> Could you be more specific with what's not working?

Before new update when i always open app it automatically update library, in simple word if any new chapter or episode came it shows me notification but after new release it does not working for me. 
I tried everything but it didn't update it. I already installed extension

**Comment by rebelonion** [comment]
There's a new notification system, so old subscriptions won't work.

**Comment by deneshwarbhandarkar** [comment]
> There's a new notification system, so old subscriptions won't work anymore.

Then how will we know that new episode or chapter came? Or added to Library? If subscription won't work?

**Comment by deneshwarbhandarkar** [comment]
> There's a new notification system, so old subscriptions won't work anymore.

I'm unable to get any new update notification..

**Comment by deneshwarbhandarkar** [comment]
> Could you be more specific with what's not working?

Are you going to add old subscription or going to continue this new subscription update.. I'm just curious

**Comment by rebelonion** [comment]
It still functions the same for the user, I just redid the whole backend for it. you just need to re-subscribe
