### ISSUE TITLE
Extension Issue

### ISSUE THREAD

**Issue by briantgosling** [rebelonion/Dantotsu#270]
looks like the torrentio extension isn't working still.
it keeps on saying...![Screenshot_2024-03-21-05-41-04-61_49c60c3b9db32cc8d20100e98d09d73d.jpg](https://github.com/rebelonion/Dantotsu/assets/116717037/55679cd0-74c6-43be-a1ab-211a81f26067)

**Comment by AbandonedCart** [comment]
It means the extension itself is broken. I think those are separate from the app.

**Comment by ni3x** [comment]
> looks like the torrentio extension isn't working still. it keeps on saying...![Screenshot_2024-03-21-05-41-04-61_49c60c3b9db32cc8d20100e98d09d73d.jpg](https://private-user-images.githubusercontent.com/116717037/314687230-55679cd0-74c6-43be-a1ab-211a81f26067.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzc2NDksIm5iZiI6MTcxMTAzNzM0OSwicGF0aCI6Ii8xMTY3MTcwMzcvMzE0Njg3MjMwLTU1Njc5Y2QwLTc0YzYtNDNiZS1hMWFiLTIxMWE4MWYyNjA2Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxNjA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDAyNjY2NTZmYWUwOTYwMGMyMDgyN2JjZWI3ZTU5OGExOTExNzA2Mjg5ODkwMzI0Yzc3OWY4OGRmMTJmMjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.omR4SaHyfcEZhqMPG8U6Hjg4mHJp7GYyz-tJtMzbplM)

You need Debrid Subscription or  Aniyomi fork [Kuukiyomi](https://github.com/LuftVerbot/kuukiyomi) to stream torrent. Dantotsu do not support torrent.

**Comment by AbandonedCart** [comment]
https://github.com/LuftVerbot/kuukiyomi/pull/56

**Comment by rebelonion** [comment]
> looks like the torrentio extension isn't working

Torrentio is still not officially supported

**Comment by AbandonedCart** [comment]
Seems like their initial design of forwarding it to a dedicated player isn't a bad compromise.
