### ISSUE TITLE
Subtitles background 

### ISSUE THREAD

**Issue by ghost** [rebelonion/Dantotsu#275]
Add an option for adjusting the background transparency of subtitles. Or maybe there could be added in the colors section for example black but semi transparent. Also there is a typo in the title when opening the "Subtitle Background Color" and "Subtitle Window Color". It shows "Outline Sub Color" for both of them.

**Comment by rebelonion** [comment]
Changing color already exists

**Comment by AbandonedCart** [comment]
So people delete entire accounts after only a day?

**Comment by sneazy-ibo** [comment]
> So people delete entire accounts after only a day?

Ts has been confusing me too, do they really make github accounts just to suggest something amd delete them directly afterwards?
