### ISSUE TITLE
A better watch order 

### ISSUE THREAD

**Issue by itsmechinmoy** [rebelonion/Dantotsu#301]
@AbandonedCart Can we have a better watch order system like that in hianime.
The current watch order only shows prequel/sequel not like season 1, 2 movies etc 
Look at this imgs:
![Screenshot_2024-03-28-09-56-14-66_572064f74bd5f9fa804b05334aa4f912](https://github.com/rebelonion/Dantotsu/assets/95120262/c92603ab-17c9-4fed-bd5c-ce206bb95bac)
![Screenshot_2024-03-28-09-56-51-48_572064f74bd5f9fa804b05334aa4f912](https://github.com/rebelonion/Dantotsu/assets/95120262/b623cdd4-1e90-4beb-8203-d1d29ccf4a19)

**Comment by rebelonion** [comment]
I've already told you that is because of the data anilist has.

**Comment by itsmechinmoy** [comment]
> I've already told you that is because of the data anilist has.

Ibo Said
![Screenshot_2024-03-28-10-02-48-24_572064f74bd5f9fa804b05334aa4f912](https://github.com/rebelonion/Dantotsu/assets/95120262/686cb082-1f05-41c5-82a1-ddc56c38ca01)

**Comment by rebelonion** [comment]
I don't know if I want scraping directly in the app.

**Comment by itsmechinmoy** [comment]
> I don't know if I want scraping directly in the app.

But it will look better 🥹

**Comment by rebelonion** [comment]
> But it will look better 🥹

this has noting to do with looks

> Way easier to move between seasons

ah that's feature would do. I totally didn't realize that was the intention... 😐

**Comment by AbandonedCart** [comment]
The only chiaki i know is the ps remote play app

**Comment by rebelonion** [comment]
> The only chiaki i know is the ps remote play app

https://chiaki.site/?/tools/watch_order

**Comment by AbandonedCart** [comment]
It was like 4th on Google.

**Comment by AbandonedCart** [comment]
I don't know about watch order, but chronological order can be done without new data

**Comment by rebelonion** [comment]
> but chronological order can be done without new data.

if it involves many anilist queries, then I'd rather not, their api has become much more restricted over the last few months.

**Comment by AbandonedCart** [comment]
Relation -> Adaptation: TV / Movie

Should be in the query for each item you already do.

**Comment by rebelonion** [comment]
> you'd need prequel / sequel (already do that) and alternatives (what's missing)

he want's all seasons. so you'd need to construct it my querying the relations.

**Comment by rebelonion** [comment]
e.g.
Date a live I -> sequel: Date A Live: Date to Date  -> sequel: Date A Live II -> sequel: Date A Live II: Kurumi Star Festival -> sequel: Date A Live Mayuri Judgement  -> sequel: Date A Live III -> etc etc etc

**Comment by AbandonedCart** [comment]
When you do a search does it grab any details about the individual items besides title and image?

**Comment by rebelonion** [comment]
yeah it grabs some of the Media info
```
id
      idMal
      isAdult
      status
      chapters
      episodes
      nextAiringEpisode {
        episode
      }
      type
      genres
      meanScore
      isFavourite
      format
      bannerImage
      coverImage {
        large
        extraLarge
      }
      title {
        english
        romaji
        userPreferred
      }
      mediaListEntry {
        progress
        private
        score(format: POINT_100)
        status
      }
```

**Comment by AbandonedCart** [comment]
![Boku no Hero Academia 5 (My Hero Academia Season 5) · AniList — Mozilla Firefox 3_28_2024 1_11_48 AM](https://github.com/rebelonion/Dantotsu/assets/1173913/fa5359f4-2e38-4c9f-9ca7-3f548caf8950)

It seems like all the information you need is available

**Comment by rebelonion** [comment]
not everything has season in the name. In fact quite a bit don't.

**Comment by rebelonion** [comment]
> e.g. Date a live I -> sequel: Date A Live: Date to Date -> sequel: Date A Live II -> sequel: Date A Live II: Kurumi Star Festival -> sequel: Date A Live Mayuri Judgement -> sequel: Date A Live III -> etc etc etc

**Comment by AbandonedCart** [comment]
The year

**Comment by rebelonion** [comment]
still not going to be accurate.

**Comment by AbandonedCart** [comment]
Nothing is going to be accurate, since they isolate the seasons

**Comment by AbandonedCart** [comment]
Actually, that's not true either. Look at demon slayer. They claim the movie is the sequel to season 1. Technically, yes. There is also a season 2 part 1, though, and that's the actual sequel.

**Comment by rebelonion** [comment]
I'm not very familiar with demon slayer, but they seem to have 2 items listed as sequel.
all the more reason why this suggestion wouldn't work.

**Comment by AbandonedCart** [comment]
Systematically going through them is definitely a bad idea.

**Comment by itsmechinmoy** [comment]
Can use anidb Instead of chiaki 
Their api is open

**Comment by rebelonion** [comment]
> Can use anidb Instead of chiaki Their api is open

They also only do prequel/sequel. You're going to have to get over it

**Comment by AbandonedCart** [comment]
I think I have something that may be a compromise.
