### ISSUE TITLE
why we are getting Rick rolled by dantotsu ?

### ISSUE THREAD

**Issue by Owlish-Gamer** [rebelonion/Dantotsu#308]
![Screenshot_2024-04-01-07-29-04-33_49c60c3b9db32cc8d20100e98d09d73d](https://github.com/rebelonion/Dantotsu/assets/133370701/76501ed1-1d03-4675-8efc-6be42ccb323b)

**Comment by rebelonion** [comment]
https://en.m.wikipedia.org/wiki/April_Fools%27_Day

**Comment by AbandonedCart** [comment]
6 PM on 3/31 is a bit early. I guess whoever launched that one was calling in sick.

**Comment by rebelonion** [comment]
Timezones are a thing. It was stated at midnight, April 1st, coordinated universal time

**Comment by AbandonedCart** [comment]
If this is 2 hours in, I can't wait for 8.

**Comment by kaorlol** [comment]
stupid ass April fools joke the app is completely unusable unless you can somehow read japanese

**Comment by rebelonion** [comment]
Ngl I'm loving the salt

**Comment by AbandonedCart** [comment]
He says, not two minutes after sounding salty.

**Comment by kaorlol** [comment]
> Ngl I'm loving the salt

blud so many new animes are coming out tmr and i dont even know if imma be able to watch them

**Comment by AbandonedCart** [comment]
Change your preferred display to romanji / english in your anilist account.

**Comment by shiftyrun** [comment]
> blud so many new animes are coming out tmr and i dont even know if imma be able to watch them

Install version 2.2.0

**Comment by shiftyrun** [comment]
> blud so many new animes are coming out tmr and i dont even know if imma be able to watch them

Install version 2.2.0. Later on, you can install a recent version after this pass away.

**Comment by shiftyrun** [comment]
@kaorlol Install version 2.2.0. Later on, you can install a recent version after this pass away.

**Comment by shiftyrun** [comment]
@kaorlol Install version 2.2.0. Later on, you can install a recent version after this event pass away.

**Comment by AbandonedCart** [comment]
I think the best parts is knowing that remote man in middle attacks are a feature.

**Comment by rebelonion** [comment]
then so is every app that uses an api ever lol

**Comment by AbandonedCart** [comment]
I don't think you understand how an API works

**Comment by Zaxx69** [comment]
Its a feature

**Comment by rebelonion** [comment]
then I don't think you understand how this was done.

**Comment by shiftyrun** [comment]
Uhh guys?

**Comment by AbandonedCart** [comment]
By all means, correct me if I am wrong. AniList is still sending out valid image urls, right?

**Comment by rebelonion** [comment]
correct. that is not the api I am talking about

**Comment by AbandonedCart** [comment]
But your API that changes the images they provide to the images you provide is the man in the middle.

**Comment by rebelonion** [comment]
my api saves a link locally that the app uses instead. I don't know if I'd consider that mitm, but It seemed like you were implying that my api was susceptible to mitm.

**Comment by AbandonedCart** [comment]
AniList does their own, but they are [all different](https://anilist.co/search/anime)

<details><summary>Demon Slayer</summary>

![anilist](https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-lEw4M4oj1u1w.jpg)
</details>

<details><summary>MASHLE: MAGIC AND MUSCLES Season 2</summary>

![anilist](https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166610-HahPxJWRxm6Y.jpg)
</details>

<details><summary>Hunter x Hunter</summary>

![anilist](https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-9azLfh1ROIX7.png)
</details>

They also have [Shrek](https://anilist.co/anime/176519/Shrek/) as a full listing

**Comment by animegamer4422** [comment]
Wait was this built into the app itself like how vlc gets a Christmas hat during December or was this done on the api side?

**Comment by rebelonion** [comment]
a little bit of both

**Comment by animegamer4422** [comment]
If the rickroll image was saved locally then it should save alot of network bandwidth instead of redownloading the same image multiple times

Btw I liked it , Happy April Fools day everyone
