### ISSUE TITLE
Timer for manga (ik anilist don't provide data)

### ISSUE THREAD

**Issue by itsmechinmoy** [rebelonion/Dantotsu#309]
Instead if possible use <https://www.mangaupdates.com/releases.html>
• This provides when the last chapter was added. They've api so dev can do something like this for mangas:
The last chapter for {manga} {chapter no} was released {time} ago

And 
<https://m.webtoons.com/en/originals>
• For manhwa and webtoons 
(Idk if they provide api or not)

**Comment by itsmechinmoy** [comment]
@AbandonedCart will you be able to do it if it's possible?

**Comment by AbandonedCart** [comment]
Do they not take feature requests here? I'm a bit confused about why I keep getting tagged for things not being part of the team when it seems like you have at least two people with time on their hands.

**Comment by rebelonion** [comment]
🤷‍♂️

**Comment by rebelonion** [comment]
people are impatient ig

**Comment by AbandonedCart** [comment]
So it was already requested and someone said it would be done when there was time?

**Comment by rebelonion** [comment]
it has been requested a few times, and I said it would be something I'd look into

**Comment by AbandonedCart** [comment]
Was this recent?

**Comment by rebelonion** [comment]
but this one is actually slightly different.
And worse.
there would be no point in using an api for when a chapter releases, as you can already subscribe to manga. The only use (and the usual request) is to use such an api for finding and displaying the total number of chapters as anilist doesn't have that.

**Comment by rebelonion** [comment]
> Was this recent?

variants have come up a few times over the lifetime of the app.

**Comment by AbandonedCart** [comment]
I had a feeling.

**Comment by rebelonion** [comment]
most of the requests I've seen you tagged in are things that have been planned to add at some point.

**Comment by AbandonedCart** [comment]
So then this is something that was planned and the fact that it contradicts the whole "AniList only client" thing isn't a concern?

**Comment by rebelonion** [comment]
being an "AniList only client" doesn't mean it can't use other apis. in case you haven't seen, the app also pulls data from kitsu and myanimelist.

but the main point of this request is a bad idea for using this api, as it already exists in another form

**Comment by rebelonion** [comment]
> I had a feeling. I was trying to understand if it was really impatience or something that either wasn't very important or not really desired, but nobody wanted to deal with saying no.

people don't always appreciate what me or the other devs prioritize. them pinging you is trying to get a feature to skip the line.
and many people have their own opinions lol. It just came up today actually. I have been pinged over 11,000 times in 4 months

**Comment by AbandonedCart** [comment]
It could also be that I don't report to anyone here.

**Comment by AbandonedCart** [comment]
@itsmechinmoy It's notting against you. You didn't make it a thing. You don't have to tag me individually, though. Ill still see it.

**Comment by AbandonedCart** [comment]
The data is definitely there. It is just a matter of matching up the specific item, since they aren't sharing IDs

**Comment by AbandonedCart** [comment]
So you were looking for something like this?

<details><summary>Count Up Timer</summary>

![Screenshot_20240402_081600](https://github.com/rebelonion/Dantotsu/assets/1173913/b0cf92bb-331f-40cd-8941-807b38cb9ef7)
</details>

I had a dentist appointment yesterday about the same time I realized I had caught the flu, so things are moving a bit slower.

**Comment by itsmechinmoy** [comment]
> So you were looking for something like this?
> 
> Count Up Timer
> I had a dentist appointment yesterday about the same time I realized I had caught the flu, so things are moving a bit slower.

Yup exactly like tht 
Can it be same for manwha and web novels?

**Comment by AbandonedCart** [comment]
I haven't looked into that yet. If the data exists, then most likely.

**Comment by AbandonedCart** [comment]
@UmbrellaalAcademy It's a nice site, but they don't have an API listed. Their source is mostly libraries used in their app that require publishing changes for license terms.

**Comment by JohnVictoryz** [comment]
actually for mangaupdates and all i found a cool kotlin api for the mangaupdates here it is: https://github.com/Mohamed-Ali-K/MangaUpdate-API

i may actually be able to make this feature if i use this but it will take time

**Comment by AbandonedCart** [comment]
It's already done. I found that one after I had already started writing a proprietary one and it cut a lot of the dead weight of retrieving stuff that'll never get used.

**Comment by itsmechinmoy** [comment]
> It's already done. I found that one after I had already started writing a proprietary one and it cut a lot of the dead weight of retrieving stuff that'll never get used.
> 
> https://github.com/rebelonion/Dantotsu/blob/dev/app/src/main/java/ani/dantotsu/connections/bakaupdates/MangaUpdates.kt

But the days are still not accurate 
Thts wht others told 
Idont read much mangas 
Just told to add this cause it was looking empty 🥲

**Comment by JohnVictoryz** [comment]
wdym i think its somewhat accurate also like from what i understand you also like want to have like a countdown from when the last chapter has been released

**Comment by itsmechinmoy** [comment]
> wdym i think its somewhat accurate also like from what i understand you also like want to have like a countdown from when the last chapter has been released

Yh it's already added
Wht I'm saying is that the countdown isn't accurate for few mangas
And it's not even working on some mangas🤷🏻

**Comment by JohnVictoryz** [comment]
> > wdym i think its somewhat accurate also like from what i understand you also like want to have like a countdown from when the last chapter has been released
> 
> Yh it's already added Wht I'm saying is that the countdown isn't accurate for few mangas And it's not even working on some mangas🤷🏻

when it is not working it is probably because it is not in mangaupdates and when it is inaccurate is probably because mangaupdates is also inaccurate because i dont see anything wrong in the code
