### ISSUE TITLE
Season tab

### ISSUE THREAD

**Issue by Light7654** [rebelonion/Dantotsu#318]
Please add a seasons or episode tab in meta data which scrap episode info from anilist
Or just show it in the info section
So that we could understand if the source is showing the right show

![Screenshot_20240403_124404_Moviebase.jpg](https://github.com/rebelonion/Dantotsu/assets/87866912/d6877f24-5f8c-463c-b405-f4a8b04bc2fc)

![Screenshot_20240403_124413_Moviebase.jpg](https://github.com/rebelonion/Dantotsu/assets/87866912/899f64b8-8e62-461d-85e9-5104707aa763)

Like this

Cause I don't know if this is showing right book

![Screenshot_20240403_123223_Dantotsu.jpg](https://github.com/rebelonion/Dantotsu/assets/87866912/8179d681-aecf-4048-b0c7-ed81ba4b5763)

**Comment by itsmechinmoy** [comment]
Client name?

**Comment by Light7654** [comment]
Anilist

**Comment by rebelonion** [comment]
Anilist separates seasons into different media items
And they already show separately

**Comment by Light7654** [comment]
I just meant that in the info tab it list out all the episodes of the show

So that we could know what's episode name and don't confuse if the source shows wrong anime

**Comment by rebelonion** [comment]
> I just meant that in the info tab it list out all the episodes of the show

unfortunately anilist doesn't have that information.
you can view the direct prequel and sequel though.
