### ISSUE TITLE
Notification count incremented on load

### ISSUE THREAD

**Issue by AbandonedCart** [rebelonion/Dantotsu#319]
Not sure if it's just me, but it seems like I am getting a ghost notification for the global message every time I restart the app. If I view my notifications, it clears. Restart the app and the count starts again. From what I can tell, there is nothing to say "I already got it, but just didn't read it" so the number keeps incrementing.

**Comment by rebelonion** [comment]
Yeah it's a known issue. Should be fixed soon

**Comment by AbandonedCart** [comment]
https://github.com/rebelonion/Dantotsu/blob/dev/app/src/main/java/ani/dantotsu/notifications/comment/CommentNotificationTask.kt#L58-L60

**Comment by rebelonion** [comment]
fixed for the next release
720b40a

**Comment by R-iscool** [comment]
> https://github.com/rebelonion/Dantotsu/blob/dev/app/src/main/java/ani/dantotsu/notifications/comment/CommentNotificationTask.kt#L58-L61
> 
> ```
>                 PrefManager.setVal(
>                     PrefName.UnreadCommentNotifications,
>                     PrefManager.getVal<Int>(PrefName.UnreadCommentNotifications) + (notifications.size)
>                 )
> ```
> 
> Doesn't solve the ghost notification, but keeps it from incrementing

How to keep it from incrementing (I'm new to GitHub please don't mind me)

**Comment by AbandonedCart** [comment]
It's supposed to be fixed in the newest build.

**Comment by R-iscool** [comment]
Ok thanks
