### ISSUE TITLE
Being able to export the progress of the episodes of an anime in your library.

### ISSUE THREAD

**Issue by Ykuzhe** [rebelonion/Dantotsu#328]
Would be nice to add this as part of the export/import feature already in the app, lost my progress awhile ago due to an update once, haven't encounter that issue again yet but having the data of your progress be saved would be a time saver for me if that issue ever happens again. I'm a bit of a perfectionist when it comes to my hobby so if it does ever happen again, it's going to bother me abit lol.

Also, if you're exporting for the first time, you should be able to atleast pick a folder where you wanna store that data and make it the default just like every other app with a 'export X' feature.

**Comment by rebelonion** [comment]
by progress do you mean what chapters/episodes you've read/watched? If so, Logging into Anilist fixes that

**Comment by AbandonedCart** [comment]
I think it means the timestamp / page

**Comment by rebelonion** [comment]
hmmm that would be pretty painful to change. Tbh I don't know if it's worth the time and effort

**Comment by Ykuzhe** [comment]
Oh really? Sorry for my ignorance then, thought it wouldn't be that hard to add it but seems like it is. You can close this as Not Planned, I don't really mind. I really appreciate the really fast replies though, keep up the great work.

**Comment by AbandonedCart** [comment]
Is the proprietary backup essential to anything?

**Comment by Ykuzhe** [comment]
> Is the proprietary backup essential to anything?

Are you talking to me? If so then I don't really understand what you mean by 'proprietary backup' but it's just that I have OCD, especially when it comes to my hobby. I'm a perfectionist when it comes to them so if I don't see the watch time line thing under episodes that i've already finished it will really bother me, I know this might seems like a realllllly stupid thing to be bothered about but yeah, sorry.

**Comment by AbandonedCart** [comment]
No, sorry. I was asking about the app.

**Comment by rebelonion** [comment]
I'm not sure what you mean either

**Comment by rebelonion** [comment]
theoretically, ``Irrelevant`` SharedPreferences could be exported, but may have unintended consequences

**Comment by AbandonedCart** [comment]
I mean does it matter that the app performs the backup manually for some purpose beyond the novelty of being able to pick items?

**Comment by rebelonion** [comment]
being able to choose what sections of settings are exported is a core feature of how the system was made

**Comment by AbandonedCart** [comment]
So users depend on the ability to only export certain sets of settings?

**Comment by rebelonion** [comment]
yes

**Comment by AbandonedCart** [comment]
Alright. I can work with that.

**Comment by rebelonion** [comment]
the simplest solution might be setting ``Irrelevant("ani.dantotsu.irrelevant", false)`` to ``Irrelevant("ani.dantotsu.irrelevant", true)``
which I can test out

**Comment by AbandonedCart** [comment]
Sure. If the unintended consequences you mentioned aren't that bad, that would be the fastest way to solve it.

**Comment by rebelonion** [comment]
that's why I want to test :)
my main worry is many things stored in ``Irrelevant`` are serialized classes.  all the serialized classes not in ``Irrelevant`` have been tested and given a ``serialVersionUID`` importing ``Irrelevant`` could cause one of those classes to fail being imported

**Comment by AbandonedCart** [comment]
As it stands now, the backup you have only supports restoring on the same device, too. I was talking more about changing the system than changing the specific items.

**Comment by rebelonion** [comment]
I was under the assumption that all individual media preferences were stored in separate ``SharedPreferences`` which apparently they might not be. iirc individual manga preferences still are.

**Comment by rebelonion** [comment]
> As it stands now, the backup you have only supports restoring on the same device, too.

I don''t think this is true. I've had many different people send me their preferences, and given mine to quite a few.

**Comment by AbandonedCart** [comment]
Sure, then we can go with "it's never worked for me"

you have a a beta/alpha/whatever preferences, one per widget, general, irrelevant, player, protected, reader, ui, logger, downloads, source, and webview chromium

**Comment by rebelonion** [comment]
> you have a a beta/alpha/whatever preferences

preferences also work between alpha/beta/release

widget were never intended to be exported.
only those in ``PreferenceInternal.Location``  tagged as such were meant to be

**Comment by rebelonion** [comment]
> Sure, then we can go with "it's never worked for me"

I'm curious what you're doing then
I haven't heard of it failing for anybody for a long time.

**Comment by AbandonedCart** [comment]
Making a backup, sending it through nearby share, and doing a restore. I didn't think the process had more steps.

**Comment by rebelonion** [comment]
> Making a backup, sending it through nearby share, and doing a restore. I didn't think the process had more steps.

you are using the export in dantotsu settings, right?

**Comment by AbandonedCart** [comment]
Is there another one?

**Comment by rebelonion** [comment]
idk if you were using you're phone's backup or something.
well if you can figure why I'd be happy to fix it.

**Comment by AbandonedCart** [comment]
I can wipe the data and get a log when I have a chance to plug it in.

**Comment by AbandonedCart** [comment]
> preference sharing also work between alpha/beta/release
> 
> widget were never intended to be exported. only those in `PreferenceInternal.Location` tagged as such were meant to be

I'm listing the files as they appear in /data/data

**Comment by rebelonion** [comment]
the more I look into this, the less I like it. Things like the download key cache are stored in ``Irrelevant``, which would cause havoc if transferred to a new device. It's definitely not impossible to work around that, but I don't think it's worth breaking everyone else's settings.

**Comment by AbandonedCart** [comment]
Aren't the timestamps and page numbers saved every time you open the stuff?

**Comment by rebelonion** [comment]
pretty much, yeah

**Comment by AbandonedCart** [comment]
The other way would be to start a dedicated preference for that. Only write to the new one. A function that checks for the old and writes it to the new. Phase the old one out over time, but then you could add backup for the new one.

**Comment by AbandonedCart** [comment]
https://stackoverflow.com/a/52546407/461982, but with some filtering

**Comment by rebelonion** [comment]
imho, I really don't think it's worth it for such a small change

**Comment by AbandonedCart** [comment]
It would be nice to put down one device, pick up another, and resume the page. I don't know that if it's been long enough since watching a video that I forgot where I was that I'd ever watch it again or not want to start over anyway.

**Comment by rebelonion** [comment]
the settings aren't sync-able. I doubt anyone other than you would rather file share and restore rather than just taking a few seconds to swipe to where you were.

**Comment by AbandonedCart** [comment]
Wait, do you think I was doing a full restore to get my page number back? I was trying to transfer my reader settings to a phone I hadn't used since setting them up.

**Comment by rebelonion** [comment]
![Screenshot_20240405_231558_Dantotsu .jpg](https://github.com/rebelonion/Dantotsu/assets/87634197/5e5d4556-250f-480e-9776-e3acb235fbc8)

**Comment by AbandonedCart** [comment]
Are you ok? Seems like you're having a completely different conversation.

**Comment by rebelonion** [comment]
![image](https://github.com/rebelonion/Dantotsu/assets/87634197/db8f07f2-0d07-4810-aae0-b54349012566)

**Comment by AbandonedCart** [comment]
I said it would be nice if the page synced between devices so I could just resume, as in without having to swipe or scroll back to it. I previously made a **completely unrelated** statement about the backup and restore not working on one device.

**Comment by rebelonion** [comment]
my man we've been talking about sharedPreferences this entire time............

**Comment by AbandonedCart** [comment]
> imho, I really don't think it's worth it for such a small change

> It would be nice to put down one device, pick up another, and resume the page. I don't know that if it's been long enough since watching a video that I forgot where I was that I'd ever watch it again or not want to start over anyway.

To clear up the confusion, what this means is sync would be nice but backup is a bit wasted. Get it now?

**Comment by rebelonion** [comment]
that has nothing to do with this feature request then.
> Would be nice to add this as part of the export/import feature already in the app

**Comment by AbandonedCart** [comment]
Sure.
