### ISSUE TITLE
How Can  You Implement Comments Per Episode System

### ISSUE THREAD

**Issue by UmbrellaalAcademy** [rebelonion/Dantotsu#339]
## **1. Episode Tagging System Implementation:** 
You'll develop a system where tags are dynamically created based on the number of episodes in the anime. This can be achieved programmatically, ensuring that for every episode, a corresponding tag is generated automatically. For example, if the anime has 24 episodes, the system will create 24 unique tags, sequentially assigned to each episode.

## **2. Automatic Tagging of Comments:** 
Once the tagging system is in place, you'll integrate it with the commenting feature of the platform. When users submit comments, the system will automatically detect which episode the comment refers to and attach the appropriate episode tag to it. This automation simplifies the process for users, ensuring that their comments are accurately tagged without manual intervention.

## **3. Filtering Mechanism Development:** 
To enable users to view comments specific to each episode, you'll implement a filtering mechanism. This functionality will allow users to select a particular episode they're interested in, and the system will filter out comments that don't have the corresponding episode tag. For instance, if a user selects episode 3, only comments tagged with the episode 3 tag will be displayed, providing a tailored viewing experience.

**Comment by AbandonedCart** [comment]
You did all that?

**Comment by rebelonion** [comment]
This screams ai

**Comment by UmbrellaalAcademy** [comment]
> This screams ai

Well the idea came to my mind and to express it properly used ai to write this 😅

**Comment by AbandonedCart** [comment]
Did you have to upgrade your plan to get the code, too?

**Comment by UmbrellaalAcademy** [comment]
> Did you have to upgrade your plan to get the code, too?
> 
> Jokes aside, aren't comments linked to the entire season pages? What happens when someone wants to make a comment about the show and they happened to be watching episode 3? What happens when someone thinks of something in episode 5 that has to do with episode 2? I don't know that the logic works when you don't have a per-episode page to justify it.

Well we've filter option so just add all and the current episode 
All will show all recent comments 
And current episode will show the comments of tht episode 

And people can just say remember tht scene in ep 2 when they're in ep 5

**Comment by AbandonedCart** [comment]
Yeah, but I'm saying people in episode 2 won't see it until episode 5

**Comment by rebelonion** [comment]
Choosing per season with tags was a conscious choice over per episode. this isn't something I feel should be changed
