### ISSUE TITLE
Manga Viewer Crashing

### ISSUE THREAD

**Issue by elucubro** [rebelonion/Dantotsu#34]
The manga viewer now crashes on most systems as a result of [commit 20acd71](https://github.com/rebelonion/Dantotsu/commit/20acd71b1a578678df702a5ce66f2b2e567855b0).

Steps to reproduce: 
Build [commit 20acd71](https://github.com/rebelonion/Dantotsu/commit/20acd71b1a578678df702a5ce66f2b2e567855b0) for pixel 4a API34 or any similar SDK, and see demonstration below

Traceback
```
FATAL EXCEPTION: main
Process: ani.dantotsu, PID: 12389 java.lang.SecurityException: ani.dantotsu: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

A possible solution is to use the following syntax, but the minimum API would have to be raised to 26
```kotlin
requireContext().registerReceiver(BroadcastReciever, IntentFilter, Context.RECEIVER_EXPORTED)
```

![dontatsu manga viewer crashing](https://github.com/rebelonion/Dantotsu/assets/114061880/6861362d-24da-437b-bd3b-717fc5f722a7)

**Comment by rebelonion** [comment]
yeah it's a new requirement in Android 14
I'll look into options

**Comment by rebelonion** [comment]
Will be fixed in the next update
