### ISSUE TITLE
[Feature Request] Manga Notification and Notification Categorization 

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#342]
As of now the notification center shows only the manga notifications along with activity notifications....
Please make it in a way that it also shows the **"manga chapter notifications"** and all the manga, anime and following/activity notifications are grouped or categorized separately , kind of like the mock up in the images below...

**The Manga chapter updates can be sourced from the subscriptions updates while checking updated chapters for subscribed manga titles.........**
### This will make it a whole lot easier to manage notifications and also keep up with all the updates ### 

![Screenshot 2024-04-08 234407](https://github.com/rebelonion/Dantotsu/assets/71634955/329350d5-ee56-484a-98d1-541208f158b5)
![Screenshot 2024-04-08 234911](https://github.com/rebelonion/Dantotsu/assets/71634955/dc889f4f-c02e-4be4-bd61-617f79aae007)
![Screenshot 2024-04-08 235207](https://github.com/rebelonion/Dantotsu/assets/71634955/78de426b-f561-44ff-b818-02a957a6cbf7)

**Comment by rebelonion** [comment]
This is something we are planning to do

**Comment by rebelonion** [comment]
Probably more a filter than separate tabs though

**Comment by kaorlol** [comment]
would also be nice to see grouping with, for example, that 'liked activity' notification, it would look better if it was grouped for multiple of the same person.

**Comment by Mathew20kdroid** [comment]
> Probably more a filter than separate tabs though 

Tabs are much more convenient right.....it kinda also matches with the overall UI aesthetics.

**Comment by Mathew20kdroid** [comment]
@rebelonion  when can we expect the **manga notification section** update in the alpha builds...
Kinda missing out on so many manga chapter updates cause they only show up in the notification center and sometimes I accidentally clear them....
Just wanted to know if it's coming anytime soon...

**Comment by Mathew20kdroid** [comment]
> @rebelonion  when can we expect the **manga notification section** update in the alpha builds...
> Kinda missing out on so many manga chapter updates cause they only show up in the notification center and sometimes I accidentally clear them....
> Just wanted to know if it's coming anytime soon...
> 

Just curious, that's all...

**Comment by rebelonion** [comment]
soon(tm)

**Comment by Mathew20kdroid** [comment]
> soon(tm)

Thank you

**Comment by Mathew20kdroid** [comment]
@rebelonion ,I think right now will be the best time to implement **Tabs section** to Notifications since **Subscription Notification** is now implemented. As of Now its too **cluttered** with too many Notifications from different sections , makes it really hard to Browse through the notifications.

**Comment by rebelonion** [comment]
I'm not really in favor of adding tabs at the moment. I'd prefer to keep it as the filter option (which is already added), as that is much more customizable than tabs.

**Comment by Mathew20kdroid** [comment]
But there are a ton of filters to enable/disable, most users will be unaware of this and doesn't have proper knowledge on which filters to select from.......

It will be a lot more **user friendly with tabs** as well...

Also if there's a separate tab for Manga then there will be no more **cloud loading** for notification for manga since they could be stored locally on the device itself (**no more notification loading cap**)

**Comment by rebelonion** [comment]
> Also if there's a separate tab for Manga then there will be no more cloud loading for notification for manga since they could be stored locally on the device itself (no more notification loading cap)

subscription notifications are already stored locally

> But there are a ton of filters to enable/disable, most users will be unaware of this and doesn't have proper knowledge on which filters to select from.......

the filters are pretty self-explanatory, If someone can't figure it out that's quite literally a skill issue

**Comment by Mathew20kdroid** [comment]
Well right now the Notification section seems a bit too cramped, that's all I'm saying
