### ISSUE TITLE
Add a manual button for updating subscription 

### ISSUE THREAD

**Issue by cututaku** [rebelonion/Dantotsu#345]
I came here from saikou and it had a option to long press the logo in setting to do a manual scan for new chapters/episodes in the subscribed mangas and animes it would really helpful 

https://github.com/rebelonion/Dantotsu/assets/166618311/837cda29-94ba-4ca7-b228-7f55f03d1b21

**Comment by cututaku** [comment]
Boy it doesn't show me when there is a new chapter i even have turned on notification from each manga

**Comment by rebelonion** [comment]
was a bug for some people that is fixed in the next version
