### ISSUE TITLE
Broken Dub Episodes

### ISSUE THREAD

**Issue by 9SYorhaDestroyer** [rebelonion/Dantotsu#349]
Hello once again creator of Dantotsufirst off thank you for fixing the broken search apparently some of the episodes of a serious I previously watched are broken and the series is I've somehow gotten stronger when I approved my farm related skills apparently episodes 8 through 12 which were all dubbed are broken and are now showing the japanese sub so please in the next update address this issue

**Comment by rebelonion** [comment]
What extension are you using?

**Comment by 9SYorhaDestroyer** [comment]
Kaido

**Comment by rebelonion** [comment]
should be fixed in the next release
