### ISSUE TITLE
Fix Animeunity

### ISSUE THREAD

**Issue by Yoshinizar** [rebelonion/Dantotsu#36]
Ho, thank you for this app, can you fix Animeunity because not find video
![Screenshot_2023-11-06-02-28-24-85_49c60c3b9db32cc8d20100e98d09d73d](https://github.com/rebelonion/Dantotsu/assets/72281082/280f685b-fc2f-4502-aba2-b8d014f06f05)
![Screenshot_2023-11-06-02-28-38-56_49c60c3b9db32cc8d20100e98d09d73d](https://github.com/rebelonion/Dantotsu/assets/72281082/33af6069-8b5f-49d6-978e-5541fa00e150)

**Comment by forsyth47** [comment]
I think its upto the aniyomi devs to flix it. Since Dantotsu just uses their extenstion to scrape the data.

**Comment by rebelonion** [comment]
Will be fixed in the next update
