### ISSUE TITLE
Tracking Chapters read on home screen

### ISSUE THREAD

**Issue by ImranMZ** [rebelonion/Dantotsu#376]
Hi i would like to request......A little count on Home screen Ui which shows how many chapters are uploaded instead of total chapters......all the continue comics just appear (~) so instead of that it should show total chapters which are uploaded till
Thank you
![Screenshot_2024-04-21-16-07-49-98_49c60c3b9db32cc8d20100e98d09d73d](https://github.com/rebelonion/Dantotsu/assets/93569556/26adf2ee-30e4-41e4-bd70-d920eabc00e6)

**Comment by rebelonion** [comment]
unfortunately anilist doesn't have that data for releasing manga.
