### ISSUE TITLE
Addressing Potential Memory Leaks in Coroutine Management

### ISSUE THREAD

**Issue by gauravsingh55** [rebelonion/Dantotsu#38]
The current implementation in `MainActivity` uses coroutines for various asynchronous tasks, such as initializing extensions and loading data. However, there's a concern regarding potential memory leaks, especially with the use of coroutine scopes.

### **Issue Details:**
- The code utilizes coroutine scopes (`animeScope` and `mangaScope`) without explicitly handling their cancellation or lifecycle awareness.
- Coroutines launched in these scopes might continue to run even after the activity is destroyed, leading to memory leaks.

### **Recommended Action:**
- Implement proper cancellation of coroutines when they are no longer needed to ensure that they don't outlive the activity.
- Consider using `lifecycle.addObserver` or other lifecycle-aware components to tie coroutine lifecycles to the activity's lifecycle.

**Comment by brahmkshatriya** [comment]
The main reason I wanted to recreate saikou.
The architecture of the app was really bad, and instead of working refactoring it, I would've really remade it.

But well, its rebelonion's call for working on fixing existing memory leaks in exoplayer.

**Comment by gauravsingh55** [comment]
> The main reason I wanted to recreate saikou. The architecture of the app was really bad, and instead of working refactoring it, I would've really remade it.
> 
> But well, its rebelonion's call for working on fixing existing memory leaks in exoplayer.

thanks for making this beautifull application. you have done a fantastic job either way!

**Comment by TobyBridle** [comment]
> But well, its rebelonion's call for working on fixing existing memory leaks in exoplayer.

I copied Saikou's exoplayer and now I see this? 🤧

**Comment by rebelonion** [comment]
despite what ChatGPT says, those Coroutines are meant to run throughout the lifecycle of the entire app.
