### ISSUE TITLE
[Feature Request] Protect App/Applock

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#380]
Please add an option to add the Applock feature in Dantotsu ....
My friends keep snooping through my phone and I like to keep my Anime/Manga list private....
Please add an Applock to Dantotsu

**Comment by JohnVictoryz** [comment]
> Please add an option to add the Applock feature in Dantotsu .... My friends keep snooping through my phone and I like to keep my Anime/Manga list private.... Please add an Applock to Dantotsu

i mean you can just use an actual applock so you can lock dantotsu

**Comment by Mathew20kdroid** [comment]
Most phones doesn't comes with an in-built Applock, and the 3rd party Applock apps are shit, not seamless and stutter all the time, also they can be bypassed if you just force stop or just uninstall the app
That's why I requested for an in-built Applock, it will make the whole process of locking the app without any hiccups.
