### ISSUE TITLE
Unable to install Novel Extensions or the Download Addons

### ISSUE THREAD

**Issue by Max20720** [rebelonion/Dantotsu#388]
Whenever I try to install any of these two things this message appears:

![IMG-20240508-WA0039](https://github.com/rebelonion/Dantotsu/assets/165971944/cdbbd825-8121-404d-9ec5-04c92e3d44ac)

"There was a problem parsing the package"

And then the download bar gets stuck like this and I can't get rid of it unless I restart my cellphone

![IMG-20240508-WA0038](https://github.com/rebelonion/Dantotsu/assets/165971944/3853432e-04d4-492b-8200-dbe33b5aab85)

**Comment by rebelonion** [comment]
I lowered the min sdk for Novel Extensions and the Download Addon
