### ISSUE TITLE
Please provide a hosturl for the parser

### ISSUE THREAD

**Issue by EGGssss** [rebelonion/Dantotsu#39]
![Screenshot_20231109-231031](https://github.com/rebelonion/Dantotsu/assets/39526433/2914ad5a-75c1-461f-b3e0-78906a1d5584)
Whenever I open a show it says, please provide a hosturl for the parser and says it can't find anything for the source.

**Comment by Sadwhy** [comment]
What source? What android version? What os? If it's aniwave then blame enimax.

**Comment by aayush2622** [comment]
Installed extensions from setting? Tried reinstalling them? clear cache? Reinstall app? Use Wifi?

**Comment by Sadwhy** [comment]
Install an extension from settings. Try gogo anime to see if it works.

**Comment by Ghibbi64** [comment]
Probabily the same error in dantotsi discord server > bugs > Only "WATCH" source placeholder is visible - bug

**Comment by EGGssss** [comment]
Thanks guys it was fixed when I installed an extension!

**Comment by Sadwhy** [comment]
🤦‍♂️
