### ISSUE TITLE
Episodes are not playing 

### ISSUE THREAD

**Issue by chaitanyamadugula** [rebelonion/Dantotsu#390]
![Screenshot_20240511-132945.png](https://github.com/rebelonion/Dantotsu/assets/118282568/c381ba8d-48a2-4b02-94e8-e70b3e710388)

**Comment by rebelonion** [comment]
this is either:
1. a broken extension (we do not maintain those here)
2. slow internet
3. a block by your isp. you can try a vpn or dns
![image](https://github.com/rebelonion/Dantotsu/assets/87634197/a3519476-733b-45d6-91d6-5ba00004b1cd)
