### ISSUE TITLE
 [Bug Report] All the Extensions from a custom repository are not showing up

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#391]
When i added a new custom github repository  via link ( **keiyoushi** ), all of the Manga extension are not showing up......some of the main ones like **ComicK, Mangareader.to** are all missing.......
i added the same in a Dantotsu Fork [Himitsu] and there all the extensions showed up......

Also please add a way or option to refresh the extensions.....

**Comment by rebelonion** [comment]
Keiyoushi are already used in app.

**Comment by Mathew20kdroid** [comment]
But some of the main extensions are missing from the main repository. i added the GitHub link "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json." but still those extensions doesn't show up....

i think this has something to do with the extension list not refreshing...

**Comment by rebelonion** [comment]
Make sure you have enabled NSFW extensions 
![Screenshot_20240511_201444_Dantotsu .jpg](https://github.com/rebelonion/Dantotsu/assets/87634197/dcfa9445-cba0-488f-838d-b6b285024ae8)

**Comment by rebelonion** [comment]
> i think this has something to do with the extension list not refreshing...

It refreshes every time you open the app.

**Comment by Mathew20kdroid** [comment]
I checked the the keyoshin website and there are still a **couple of major extensions missing**...
Does it have anything to do with **older versions**??
I saw the missing extension were unupdated( **version number marked red**)

**Comment by Mathew20kdroid** [comment]
I used a **different app** to check for extensions and all these missing ones show up there... a
Also there was an update to **ComicK extension** which is also not showing up in Dantotsu extensions
