### ISSUE TITLE
Player error 4003

### ISSUE THREAD

**Issue by Zeero59** [rebelonion/Dantotsu#392]
![Screenshot_20240514-071547.png](https://github.com/rebelonion/Dantotsu/assets/106791668/721f2e27-95a9-4ac2-8bae-e2fdf5e838af)

After my system update(a14) the app gives this error when I pause the video or close the screen and try to play it again.

**Comment by rebelonion** [comment]
hey, does this happen every time?
Have you tried different sources?

**Comment by Zeero59** [comment]
Yeah it seems like a compatibility issue with the custom rom I use.
I tried different roms but the issue persists.
Do you have any idea what could be causing this?
Of course Ur free to dismiss this as it's an incompatibility with the OS.

**Comment by rebelonion** [comment]
after some digging, it seems error 4003 is ``ENCODING_FORMAT_UNSUPPORTED`` 
https://github.com/google/ExoPlayer/blob/9c9f5a0599ec012d5cc46e3bd2e732a589adf61d/library/transformer/src/main/java/com/google/android/exoplayer2/transformer/ExportException.java#L157
so it seems to be that exoplayer doesn't seem to think that rom is capable of playing that codec.

**Comment by Zeero59** [comment]
I got annoyed and changed my custom ROM
Now it works just fine.

**Comment by lazer-007** [comment]
Hello, I am also getting the same error but only on torrentio. I am not on custom ROM, hyperOS. I have no idea why this is happening.
