### ISSUE TITLE
UI loading insanely slowly

### ISSUE THREAD

**Issue by WeepingClown13** [rebelonion/Dantotsu#4]
After the opening the app, there's a huge delay to load the UI. The logo is shown right upon the launch and then the spinner takes quite long to finish. I currently am on a rather high speed network, so it feels more than just a network thing. Saikou seems to load almost instantly as well, so I assume there is something else here that forces this delay.

**Comment by rebelonion** [comment]
What android version are you using?
Does wifi make a difference?
Or the DNS in settings?
And how long is insanely slow?
virtually nothing has changed in how data is loaded from Anilist compared to Saikou.
I've seen no other reports of this so far, but I'll look into it.

**Comment by WeepingClown13** [comment]
I am using Android 13. Good point on dns because it does seem to fix the problem, but this means relying on something external as internally changing dns results in losing internet connectivity in my phone. What's even more strange is how you mentioned there's virtually no change from Saikou, because Saikou is indifferent to anything and loads properly in both scenarios, so there definitely is something to this. If you need a measurement of how slow the process is, at bare minimum it takes 10s, and if network is slow, much higher. Although in the latter scenarios instead of loading the screen late it actually loaded ![blank screens](https://github.com/rebelonion/Dantotsu/assets/95921427/a5422329-6f9e-4b70-801d-4e904497b5f8) all the time.

**Comment by WeepingClown13** [comment]
I am using Android 13. Good point on dns because it does seem to fix the problem, but this means relying on something external as internally changing dns results in losing internet connectivity in my phone. What's even more strange is how you mentioned there's virtually no change from Saikou, because Saikou is indifferent to anything and loads properly in both scenarios, so there definitely is something to this. If you need a measurement of how slow the process is, at bare minimum it takes 10s, and if network is slow, much higher. Although in the latter scenarios instead of loading the screen late it actually loaded blank screens all the time![ss](https://github.com/rebelonion/Dantotsu/assets/95921427/a5422329-6f9e-4b70-801d-4e904497b5f8)

**Comment by rebelonion** [comment]
did you change the dns in your phone settings?
I meant try the dns in Dantotsu settings

**Comment by WeepingClown13** [comment]
Yes, that's a working solution as well. I had the same dns set in Saikou as well (although once again it works normally regardless). Anyway since there is a working solution, I'll close this, hopefully it won't be happen again. In the off chance it happens we can reopen this and have further discussions, I guess. Thanks for staying on top of it!
