### ISSUE TITLE
Unable to play HEVC videos

### ISSUE THREAD

**Issue by JiyaYin** [rebelonion/Dantotsu#408]
Videos with HEVC format are not playable with the Dandotsu internal player. Only MKV and some AVC works. I've tried using external player such as VLC and it works just fine there. Receiving an error when playing internally "Player Error 4003 (ERROR_DECODING_FAILED)"

**Comment by Sadwhy** [comment]
Same problem 
![Screenshot_20240522_165447_Nice_Catch](https://github.com/rebelonion/Dantotsu/assets/99601717/f0a02eb7-0e11-4c65-8e4b-ccac5d67c55f)

**Comment by Sadwhy** [comment]
This issue will be fixed once #528 is merged.
