### ISSUE TITLE
[Bug] Subscriptions not updating

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#409]
I'm using the latest alpha version and the subscriptions are not getting updated , the subscription checking notification gets stuck after checking for the first one....
And the notification persists in the notification panel....

![Screenshot_20240531-111425.png](https://github.com/rebelonion/Dantotsu/assets/71634955/708609fd-c649-44f2-9ecc-80d26e09aec1)

**Comment by rebelonion** [comment]
Please don't make bug reports on GitHub for alpha :)
If you have access to the alpha build, you have access to the correct channels to make a report.

**Comment by Mathew20kdroid** [comment]
Okay, sorry about that...
