### ISSUE TITLE
Episodes are shown backwards 

### ISSUE THREAD

**Issue by MRGABOZ** [rebelonion/Dantotsu#41]
The chapters in the animemovil extension are shown backwards. The first is the last and the last is the first 
![Screenshot_20231112_083554_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/32cf407a-2364-4dec-8bcd-fab4b2a60b83)
![Screenshot_20231112_083339_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/d7c73cfa-d868-45a1-8340-98c3734d3d37)

I would appreciate if you can fix that.

**Comment by rebelonion** [comment]
Will be fixed in the next update
