### ISSUE TITLE
[Feature Request] Editable global default source.

### ISSUE THREAD

**Issue by watermelvin** [rebelonion/Dantotsu#410]
It would be convenient to have a user configurable default source instead of always defaulting to the first alphabetical source. This is primarily for manga sources, but anime sources would also benefit.

**Comment by sneazy-ibo** [comment]
The default source used for anime and manga is the on at the top of your extension list. It's possible to drag and drop them and whenever no media is found with the first source it cycles to the next one till it finds a media with the correct title

**Comment by watermelvin** [comment]
Thanks, don't know how I missed that!
