### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by MRGABOZ** [rebelonion/Dantotsu#42]
The jkanime extension is not working. I have already checked and it is working in aniyomi 
![Screenshot_20231112_084558_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/13bc1fba-91bf-4318-90e8-15ddd050a998)
![Screenshot_20231112_084451_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/3ac60f94-d2b4-4bae-99b0-38853c16a5b6)
![Screenshot_20231112_084515_Animiru](https://github.com/rebelonion/Dantotsu/assets/127360522/48687f39-bde7-4a34-9039-fc509c0bd489)

**Comment by rebelonion** [comment]
Will be fixed in the next update
