### ISSUE TITLE
Can't find any available anime extensions.

### ISSUE THREAD

**Issue by Sateru-gojo** [rebelonion/Dantotsu#425]
Literally my available anime section is totally empty.  It doesn't show any extensions. So now what I couldn't figure anything out I tried everything. Clear cache, re-installing the app, make sure it's the latest version. 🙏🙏
![Screenshot_20240615_204701_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/172917174/8f19aa0b-9bb3-4e0e-8e58-fda5eed2c349)

**Comment by towermom9** [comment]
can you check the extensions repo?

**Comment by Sateru-gojo** [comment]
> can you check the extensions repo?

Yeah. But what to do? I don't understand tbh.

**Comment by itsmechinmoy** [comment]
You guys are one Google search away to find working aniyomi repos

**Comment by towermom9** [comment]
> You guys are one Google search away to find working aniyomi repos

yeah... the official aniyomi repo got ~~nuked~~ (DMCA'ed) https://aniyomi.org/extensions/

**Comment by itsmechinmoy** [comment]
@Sateru-gojo close this issue cause we can't recommend ext repos 
> Official aniyomi extensions repo got dmca

**Comment by King000000000000000** [comment]
So what's the solution? 😓

**Comment by itsmechinmoy** [comment]
> So what's the solution? 😓

google

**Comment by King000000000000000** [comment]
> > So what's the solution? 😓
> 
> google

https://raw.githubusercontent.com/almightyhak/aniyomi-anime-repo/main/index.min.json
Nevermind I found the solution 🗿✨👍

**Comment by itsmechinmoy** [comment]
> Nevermind I found the solution 🗿✨👍
 don't send repo links here wtf

**Comment by King000000000000000** [comment]
> > Nevermind I found the solution 🗿✨👍
> 
> don't send repo links here wtf

Why? 🥺

**Comment by sneazy-ibo** [comment]
> > don't send repo links here wtf
> 
> Why? 🥺

Because it's not allowed and will get the app banned.

**Comment by Blade1170** [comment]
> > No importa, encontré la solución 🗿✨👍
> Cuál es la solución?

**Comment by Blade1170** [comment]
> > > Entonces ¿cuál es la solución? 😓
> > 
> > 
> > Google
> 
> No importa, encontré la solución 🗿✨👍

Cuál es la solución, me puedes ayudar?

**Comment by itsmechinmoy** [comment]
> Cuál es la solución, me puedes ayudar?

google
