### ISSUE TITLE
playing a fully watched episode again should play it from the start

### ISSUE THREAD

**Issue by WeepingClown13** [rebelonion/Dantotsu#43]
If an episode is fully watched, the next time it is opened, it just recognises the completion and forces the next episode to load. If you, for example, fall asleep at e5 and it plays till e10, the next time to just start e5 you have to put in some garagantuan effort because it'll keep loading the next episodes since they are all marked as finished. And then after you go back to e5, this happens again. The only solution is to somehow manage to pause the next episode loading and the micromanage it. This has been an issue that's been plaguing me since Saikou. Yes, this only happens when autoplay is enabled, I think that should only apply to an on-going session. When something finished is opened again, it should be starting from the beginning, lest there is no proper way to revisit it.

**Comment by rebelonion** [comment]
fixed in v2.0.0
