### ISSUE TITLE
Need MAL Anime Content Search List support

### ISSUE THREAD

**Issue by rajinstar** [rebelonion/Dantotsu#476]
I request you to please add a database from MAL with Anilist. When I search for any anime then I should get an anime list from MAL-Anilist (combined and show one list). Because, some anime or special episodes are not available in Anilist's Database, only MAL has a huge database of Anime. If I use both (MAL and Anilist) the database search results in one app. This will be the game changer for me. I sometimes watch some special episodes of my favourite anime. But, I didn't find any in Anilist but in MAL. That's why I mostly use MAL instead of Anilist. I am requesting you please consider my proposal. Pls😫

**Comment by itsmechinmoy** [comment]
Wrongtitle exists 
Also dantotsu is an anilist only client not a mal-anilist hybrid

**Comment by rajinstar** [comment]
@itsmechinmoy, I know. But I am requesting that MAL has a huge database At least I can find some anime that are only available up until now in MAL and will very soon be updated to Anilist. I am not saying make the app a hybrid. I am saying Aniyomi has the option to search for any anime available in the extension whether it is available in MAL or Anilist. It doesn't matter. It will also increase the convenience for me to watch anime and enjoy my leisure time.

**Comment by itsmechinmoy** [comment]
> @itsmechinmoy, I know. But I am requesting that MAL has a huge database At least I can find some anime that are only available up until now in MAL and will very soon be updated to Anilist. I am not saying make the app a hybrid. I am saying Aniyomi has the option to search for any anime available in the extension whether it is available in MAL or Anilist. It doesn't matter. It will also increase the convenience for me to watch anime and enjoy my leisure time. 

Use the wrong title option

**Comment by rajinstar** [comment]
@itsmechinmoy, 

This screenshot will show you this anime is available in MAL:

![Screenshot_2024-09-15-16-10-58-054_net.myanimelist.app.jpg](https://github.com/user-attachments/assets/379e44b3-c69b-48c0-a03b-47cbe5610e14)

This screenshot will show you this anime is unavailable in Dantotsu:

![Screenshot_2024-09-15-16-11-49-315_ani.dantotsu.beta.jpg](https://github.com/user-attachments/assets/20f05974-06ef-42f7-9d0f-6f2976800388)

That's what I am talking about. Please do something 😭.
