### ISSUE TITLE
Unexpected error prevents me from logging into the extension website to watch.

### ISSUE THREAD

**Issue by Vhiniz** [rebelonion/Dantotsu#477]
The problem occurs with some extensions, but not all. The worst part is that I need to access the betteranime extension website to log in. 

Extension: betteranime (pt-br)

https://github.com/user-attachments/assets/0a2a7fb1-6675-4e0e-a2f3-ab0c18a73f2f

**Comment by rebelonion** [comment]
We don't officially support extensions here, but seems like the extension is broken.

**Comment by Vhiniz** [comment]
> We don't officially support extensions here, but seems like the extension is broken.

This same problem occurs in another application that also uses the same extension, but the difference is that the web version has arrows to go back. So every time this happens I click the "back" button and I can use the web version. See this in the attached video.

Wouldn't it be possible to add this to Dantotsu?

(sorry for the ads, there's nothing you can do about it)

https://github.com/user-attachments/assets/953314ac-2f34-4fe6-8fc0-cd3685cdfa51
