### ISSUE TITLE
Request for a change in features. 

### ISSUE THREAD

**Issue by f4rh4d-4hmed** [rebelonion/Dantotsu#481]
Hello,

I really appreciate that Dentotsu has a lock feature. I've used it, and while I’m not sure how secure it is, the fact that it locks the UI is what matters most to me. However, I’ve noticed a problem—when I type in my password, it’s visible on the screen. This is an issue because if I’m entering it in front of my little brother or sister, they’ll definitely see it and try to sneak in later.

It would be great if you could make it so that the password is hidden while typing, like how most apps show dots or asterisks. That would solve the problem and make it more secure.

Thank you in advance!

**Comment by grayankit** [comment]
looks like the dev intent was to make it sneaky and hide it like a calculator

**Comment by f4rh4d-4hmed** [comment]
@grayankit It looks like calculator. Well maybe it's batter that way. I take it back what I said. Thank you for pointing it out.
