### ISSUE TITLE
Search field not focusing on click in anime browsing page

### ISSUE THREAD

**Issue by MightyCoderX** [rebelonion/Dantotsu#484]
When clicking on the search field on the anime page it doesn't focus like it does in the manga page.

https://github.com/user-attachments/assets/cb51155c-900f-4ed4-9a8a-cab73b1aa02f

I would like to try and fix this myself, since it looks like it _should_ be quite easy. Could someone guide me to where I can find the place where this is implemented in the manga page? It's my first time trying to fix, even if it is a small bug, in a project this big.

**Comment by grayankit** [comment]
It is fixed already in the alpha version of app.

**Comment by MightyCoderX** [comment]
ok

**Comment by MightyCoderX** [comment]
@grayankit could you point out the commit?

**Comment by grayankit** [comment]
79742f415bec098776b7b6c40fee7dd355aa6518 I think this one
