### ISSUE TITLE
No Update For 5 Months Are You Going To Be Shut Down By DMCA Or  Operation Anime Soon

### ISSUE THREAD

**Issue by 9SYorhaDestroyer** [rebelonion/Dantotsu#485]
Hello once again creators of Dantotsu I'm sending you a message because you have an updated your app since May now I know you probably have some stuff going on in your personal life with your actual job and this is probably a hobby but just tell me are you going to going to be shut down or not just tell me just tell me you're not going to be shut down and then you're focusing on the next update with you and your team please just tell me I look forward to your response to my issue I have or if you don't that means to me that you are going to be shut down and that I had to look for another alternative like I have done many times before

**Comment by sneazy-ibo** [comment]
Stable and Beta are updated every once in a while. However the Alpha version that you can get on the discord server or [here](https://github.com/kaorlol/dantotsu-updater) used to be get updates almost every day but he maintainer is currently busy irl and contributors like me and others have moved on.

Regarding the shutdown, there is no DMCA that has been filed or anything different. The devs are just currently working on different things.

**Comment by grayankit** [comment]
@9SYorhaDestroyer Close the issue
