### ISSUE TITLE
Reading a decimal chapter registers as a whole chapter in trackers

### ISSUE THREAD

**Issue by Ovi329** [rebelonion/Dantotsu#49]
1. When I finish chapter no. 128.1 it updates as chapter 129 on anilist and Mal. I think these decimal chapters should be ignored and not be counted as a whole chapter. Usually the author of the manga releases these on Twitter. And if there are many decimal chapters, they add up on anilist and Mal and when the whole manga is completed there are more chapters than the actual number of chapters that the author released. 
2. Volume and brightness of the player should be remembered once it's exited. It'd also be cool to add numbers to the volume and brightness slider for precision. (Aniyomi has it)

**Comment by Ovi329** [comment]
Are these gonna get fixed?

**Comment by rebelonion** [comment]
1. for sure
2. maybe eventually

**Comment by rebelonion** [comment]
1. fixed in next beta
