### ISSUE TITLE
Failed to bypass cloudflare

### ISSUE THREAD

**Issue by f4rh4d-4hmed** [rebelonion/Dantotsu#492]
![Screenshot_20241006_223313_Dantotsu](https://github.com/user-attachments/assets/a735c0fc-0b05-450c-b1a0-d20de84a61b9)
I tried with different vpn. But the outcome is still same. Unfortunately I can't find log files.

**Comment by JurasDss** [comment]
I have the same problem

**Comment by atharvbambal** [comment]
Same prob, might be a universal issue

**Comment by Xynonners** [comment]
yup

**Comment by f4rh4d-4hmed** [comment]
Its working again. The problem seem was with api. I hope a alternate can be found to fix the issue.

**Comment by JasonBlitz5** [comment]
![Screenshot_20241006_124443_Discord.jpg](https://github.com/user-attachments/assets/06c0d943-0a92-4988-bf4c-0363b24a7386)

Anilist has blocked the API so that's why

**Comment by AasV21** [comment]
I have am facing the same issue what should I do ?

**Comment by f4rh4d-4hmed** [comment]
If you're facing the problem right now, just wait for it to be fixed automatically. The Anilist api is down for around 4-6 hours now. It may wake up any moment @AasV21

**Comment by Tanik-0967** [comment]
> I  am facing the same issue what should I do It's not only you it's happening with everyone.
API problem
