### ISSUE TITLE
Screen rotates in opposite automatically when video starts playing 

### ISSUE THREAD

**Issue by i486** [rebelonion/Dantotsu#51]
When using the application on my tablet in landscape mode with auto rotation turned off, I noticed an inconvenience in the video playback experience. Here's a breakdown of the issue:

1. I set my tablet to landscape mode and disable auto rotation.
2. I launch Dantotsu, and it starts in the same landscape mode as prior to launching the app, which is expected and desirable.
3. I select an episode, choose the video source, and when the video starts, it auto rotates to reverse landscape.

This auto rotation behavior forces me to tilt the tablet significantly to make the "rotate" button appear on the app, click it, and then watch the video. This disrupts the experience, especially when using the tablet in a bed, like laying on my bedside.

<a href="url"><img src="https://github.com/rebelonion/Dantotsu/assets/625325/5792117b-f6fa-49a5-a3fa-a35e747292b4" height="480" ></a>

I kindly request the developer to consider adding an option in the application settings to address this auto rotation behavior. 

- Disable Auto Rotation: Provide a toggle in the settings that allows users to completely disable the auto rotation behavior, ensuring the app respects the landscape mode set by the user.
- Respect Landscape Mode: Alternatively, add an option for the app to respect the landscape mode that was initially set when the video starts, instead of automatically rotating to reverse landscape.

Implementing either of these options would greatly enhance the user experience, especially for those who prefer to use their tablets in specific orientations without constant auto rotation adjustments.

**Comment by rebelonion** [comment]
thx I'll look into it

**Comment by i486** [comment]
You fixed this didn't you and also added rotation by censor which is super helpful. Thank you very much.

**Comment by rebelonion** [comment]
I couldn't reproduce on my end, so I took a shot in the dark and hoped it would help. glad to hear it did :)
