### ISSUE TITLE
Anilist user data not loading upon app startup 

### ISSUE THREAD

**Issue by AasV21** [rebelonion/Dantotsu#517]
### Steps to Reproduce

1. Open the app
2. Navigate to the home tab
3. Click on profile photo 

### Expected Outcome

1. Able to see all my animes and manga
2. Show my user account details 
### Actual Outcome

 App is constantly displaying these messages 
1. Error loading Anilist user data 
2. Error fetching Anilist data: Failed to bypass Cloudflare
3. Saying "No user found"

### Dantotsu Version

3.1.0

### Operating System Version

Android 14

### Device Information

Realme P1 5G 

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/rebelonion/Dantotsu/latest)** version of Dantotsu. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by Owlish-Gamer** [comment]
I'm also having same issue

**Comment by vulcanrvn90** [comment]
Same issue as well has been on and off for the last few days. Anilist site is working each time error occurs.

**Comment by AasV21** [comment]
Hope they fix it soon

**Comment by manuelmolinaf** [comment]
Same here

**Comment by Dawn-used-yeet** [comment]
It is an anilist **api** issue. We can do nothing about it.
You just have to wait for them to fix it. Nothing is wrong with your app and you aren't banned.
Just wait patiently. If you want more information. 
Contact anilist : https://discord.gg/anilist

**Comment by Sai-9305** [comment]
Anyone know if its fixed been having the same problem and I literally first started using it yesterday.

**Comment by Jhaneeks** [comment]
Also having the same issue ..hope it's fixed because i really love this app

**Comment by Sai-9305** [comment]
> > Anyone know if its fixed been having the same problem and I literally first started using it yesterday.
> 
> > It is an anilist **api** issue. We can do nothing about it. You just have to wait for them to fix it. Nothing is wrong with your app and you aren't banned. Just wait patiently. If you want more information. Contact anilist : https://discord.gg/anilist
> 
> People really ignored this lol

Nah I went to their Discord and they say it should be alright for most but obviously some still got problems

**Comment by Dawn-used-yeet** [comment]
> > Anyone know if its fixed been having the same problem and I literally first started using it yesterday.
> 
> > It is an anilist **api** issue. We can do nothing about it. You just have to wait for them to fix it. Nothing is wrong with your app and you aren't banned. Just wait patiently. If you want more information. Contact anilist : https://discord.gg/anilist
> 
> People really ignored this lol

![tys57wq3arpd1](https://github.com/user-attachments/assets/5ace0b7d-7457-4640-a89e-cc17a56a70a0)

**Comment by Sai-9305** [comment]
> > > Anyone know if its fixed been having the same problem and I literally first started using it yesterday.
> > 
> > 
> > > It is an anilist **api** issue. We can do nothing about it. You just have to wait for them to fix it. Nothing is wrong with your app and you aren't banned. Just wait patiently. If you want more information. Contact anilist : https://discord.gg/anilist
> > 
> > 
> > People really ignored this lol
> 
> ![tys57wq3arpd1](https://private-user-images.githubusercontent.com/185235492/384703743-5ace0b7d-7457-4640-a89e-cc17a56a70a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTQyMzIsIm5iZiI6MTczMTI1MzkzMiwicGF0aCI6Ii8xODUyMzU0OTIvMzg0NzAzNzQzLTVhY2UwYjdkLTc0NTctNDY0MC1hODllLWNjMTdhNTZhNzBhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjE0MDc2NTZmMmNjZWFiMzhmMTE0NDE2ODhmNGU2Yjg3MzJiYzEzMTE3N2YzYjRhY2ExOTFhMWEwOTNmNDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tZqu4N8GCkZu2U2pLKYocz72zg1o5HQLmE_v0frm21M)

Nah I went to their Discord and they say it should be alright for most but obviously some still got problems

**Comment by AasV21** [comment]
The api is working again I guess I am able to use the app now

**Comment by AasV21** [comment]
The api is working again I guess I am able to use the app now

**Comment by chaosmyth007** [comment]
Same issue!
