### ISSUE TITLE
Cannot Play Torrent Files in Dantotsu by Using WSA

### ISSUE THREAD

**Issue by rajinstar** [rebelonion/Dantotsu#535]
### Steps to Reproduce

1. Install WSA (Windows Subsystems for Android) in my Laptop. 
2. Install Dantotsu app in my PC.
3. Install Torrent Add-on in my Dantotsu.
4. Install Torrent Extension to my Dantotsu.
5. Go to any Anime.
6. Select Torrent Extension.
7. Click on any video
8. Boom, not playing any video.

### Expected Outcome

The app should play Torrent files as expected just like it runs to my phone without any problem.

### Actual Outcome

The app doesn't play Torrent files. 
![IMG_20241130_154555](https://github.com/user-attachments/assets/66d4660f-5c11-479b-8b6a-0c022043bab7)

And show above message!

### Dartotsu Version

3.1.0-alpha01-f62bdf93

### Operating System Version

Android 13 (WSA)

### Device Information

MSI Modern 15 A5M

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/rebelonion/Dantotsu/latest)** version of Dantotsu. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
https://www.reddit.com/r/Windows11/s/NIAfwkInYA

**Comment by rajinstar** [comment]
@itsmechinmoy I am using WSABuilds github. They continuously support the program. I know the app is no longer available but WSABuilds support WAS after Microsoft officially ended up supporting it.
