### ISSUE TITLE
No Streams Available On HiAnime And Kaido Server 

### ISSUE THREAD

**Issue by 9SYorhaDestroyer** [rebelonion/Dantotsu#543]
### Steps to Reproduce

The problem occurred a week ago when I was trying to watch the latest new episodes of some my new favorite anime the error message popped up on kaido or hianime and I thought that I'd be episodes were not available yet but when it was way past the day it was available in Japan before being available for streaming in us the error message kept popping up no matter what thus I had no choice but to go through another source another server which was anime p a h e and somehow it worked but not for when the anime specifically had an English dub release too so please fix it whenever you have a chance

### Expected Outcome

N/A

### Actual Outcome

The error message kept popping up on most of my recently watching anime or some of the ones that I'm re-watching it only pops up on those when I'm using kaido or hianime but the only server where the message doesn't pop up is animepahe 

### Error Logs (if applicable)

N/A

### Dartotsu Version

3.10

### Operating System Version

Android 14 One UI 6

### Device Information

Samsung Galaxy A15 5G 

### Additional Information

N/A

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/rebelonion/Dantotsu/latest)** version of Dantotsu. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
We do not maintain extensions 
Close this issue

**Comment by 9SYorhaDestroyer** [comment]
N/A
