### ISSUE TITLE
Problem with player 

### ISSUE THREAD

**Issue by Weinyrie** [rebelonion/Dantotsu#551]
### Steps to Reproduce

Open any anime or manga go to watch/read 

![Screenshot_20241228_233004_ani dantotsu_edit_2516162742321270](https://github.com/user-attachments/assets/ca3d46eb-e1cd-4a5f-bda8-e14c07537b3d)

### Expected Outcome

See multiple and be able to select different sources

### Actual Outcome

Cant select anything except the downloaded also cant access the setting button to its side

### Dartotsu Version

3.1.0

### Operating System Version

Emui 12.0.0 (android 10)

### Device Information

Huawei p30 Pro

### Additional Information

I havent downloaded any plug-in or extensions ive already installed and uninstalled multiple times and nothing seems to work the offline mode in app works fine so i dont think its because im stuck in offline mode, the app is fresh out of install. 

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/rebelonion/Dantotsu/latest)** version of Dantotsu. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
Dantotsu doesn't maintain extensions.
If the extension doesn't work we will not be able to help you.
Contact owner of Respective Repo for extension related problems.

**Comment by Weinyrie** [comment]
Oh ye i just joined discord. Sorry im new in dontotsu was living with saikou up until now lol. Had to search why saikou servers was getting buggy n stuff n was forced here lmao
