### ISSUE TITLE
Material Ui is not working 

### ISSUE THREAD

**Issue by Root-Time** [rebelonion/Dantotsu#56]
If I activate Material Ui. The Background is still pitch dark. (My Material is not pitch dark) 

I did a restart.
I am on beta03 ( Version 2 )

![Screenshot_20231121-103700](https://github.com/rebelonion/Dantotsu/assets/76535404/e9ed3a43-724a-471e-99d7-06c76eef7261)

**Comment by rebelonion** [comment]
do you have use oled theme variant on?
