### ISSUE TITLE
Is there any way to implement extensions like the cloudstream app without actually needing to install the extension as an app?

### ISSUE THREAD

**Issue by randomcloudswings** [rebelonion/Dantotsu#58]
As I mentioned in title, is it possible? (Sorry if these type of questions are not allowed in issues)

**Comment by ARIF683** [comment]
![IMG_20231123_222455.jpg](https://github.com/rebelonion/Dantotsu/assets/70383209/4802a691-cd28-4e6b-ab89-8fc13d851ee0)

Maybe in future.

**Comment by AbandonedCart** [comment]
Trying to submit to the Play Store is seppuku. Foreground services are out, unless justified as absolutely necessary. Package installation is out. You need 100 confirmation dialogs. Discord integration will be a costly feature. It's a literal nightmare.

**Comment by itsmechinmoy** [comment]
> As I mentioned in title, is it possible? (Sorry if these type of questions are not allowed in issues)

Use [Dartotsu](https://github.com/aayush2622/Dartotsu)
