### ISSUE TITLE
Extension not updating/downloading in the current beta

### ISSUE THREAD

**Issue by priyanshu8017** [rebelonion/Dantotsu#60]
Updating or downloading an extension in the beta3 stucks. It keeps loading. I had to install the stable 1.0.0 version to successfully update those extensions. 
![Screenshot_20231126-085313_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/102169180/8a040816-a762-4d55-8b9d-4062ae76855c)
![Screenshot_20231126-085309_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/102169180/e8f54e38-e645-4d4a-ae48-8d59cdb07a88)

**Comment by rebelonion** [comment]
do you have android 14?

**Comment by priyanshu8017** [comment]
Using Android 12

**Comment by rebelonion** [comment]
well I updated some stuff in the background to support the latest version of android and it broke some things,
Will be fixed in the next update.
