### ISSUE TITLE
Downloaded pages are not in original order

### ISSUE THREAD

**Issue by Misbah-Raza** [rebelonion/Dantotsu#64]
After downloading manga pages are not in right order plx fix it

**Comment by aayush2622** [comment]
pls dont make another issue for same prob :pray~1:

**Comment by Misbah-Raza** [comment]
> pls dont make another issue for same prob :pray~1:

Ok sorry so one answered me about problem so i thought making another issue do you know anything about this problem if you know plz help me

**Comment by aayush2622** [comment]
@rebelonion will look into it

**Comment by aayush2622** [comment]
@Ari bro literally brought that post from its grave

**Comment by rebelonion** [comment]
Will be fixed in the next update
