### ISSUE TITLE
[Video player]  gesture for brightness , doesnt give control back to android  when disabled , until app is forcestop restarted

### ISSUE THREAD

**Issue by blackholeearth** [rebelonion/Dantotsu#75]
**İssue:**
1) open any anime in Video player,  
2)  swipe up  brightness with gesture , 
3) disable gesture for brightness and volume .
4) when playeyer is open , swipe down android quick panel , try to change brightness.
5) it says " Brighness is controlled by app ...."

App doesnt give control back to android  when brightness gesture is disabled.

**Expected**
When brightness gesture is disabled, 
app should
Release  brighness control rights back to 
Android system (aka quick panel ,)

**Device:** 
Samsung a12 - android 12 - core ui 5

-------
**Edit2**: 
İ checked the app again. 
1) Gesture is disabled.
2) İ killed app . Restarted
3) Opened random anime. Now in player.
İ can change  brightness.  AppPlayer doesnt block android qpanel Brightness .
 all good. 👍👍

**Request : alert the user pls:**
When user is switching it off.
Pls, show a message

 "to release brighness lock to android system. Yoy have to kill and restart the app. "

Or
 better kill process restart itself after message , if the android allows it

**Comment by Adolar0042** [comment]
That doesn't seem to be normal android behavior, mind telling me the manufacturer of your phone?

**Comment by aayush2622** [comment]
Lurker coming out of the dark

**Comment by rebelonion** [comment]
I think this is a device specific problem
I can't reproduce on my phone or any emulator
I'll see about notifying the user tho
