### ISSUE TITLE
18+ sorces don't show any manga

### ISSUE THREAD

**Issue by farzana840** [rebelonion/Dantotsu#78]
When using 18+ sources, it detects the title but fails to load and fetch the manga from the source. "Couldn't find anything. Try another source". Tried with 5 sources. plx fix. Thank you

**Comment by Zaxx69** [comment]
Can you share the name of the dou jin if you don't mind

**Comment by Sadwhy** [comment]
Problem is that there isn't any unified source that reliables hosts 18+ manga. Different extensions have different manga. Some has only one chapter of that(nhentai) and some the whole series. It's very spread out so I recommend searching through every source. @rebelonion worthy of a "wontfix" perhaps?

**Comment by rebelonion** [comment]
no response
