### ISSUE TITLE
Episode size shown is 0 MB

### ISSUE THREAD

**Issue by WeepingClown13** [rebelonion/Dantotsu#8]
Size for episodes is being shown as zero in the UI. Getting it for Animepahe and I confirmed this across different anime. No idea about others as I usually use Animepahe itself and the other builtin Myanime never works. There is no issues with the downloads or watching the anime, only the size is always being displayed as zero for everything.![Screenshot_20231024_034316_Dantotsu.png](https://github.com/rebelonion/Dantotsu/assets/95921427/6fcdc573-c41c-48e4-bbbf-7ac9511a2765)

**Comment by rebelonion** [comment]
thx I'll look

**Comment by rebelonion** [comment]
Will be fixed in the next update
