### ISSUE TITLE
After installing a bunch of nsfw extensions, how do you browse?

### ISSUE THREAD

**Issue by sombresu** [rebelonion/Dantotsu#82]
The browse anime doesn't find anything nor showing nsfw anime. I tried to enable nsfw setting if there were such thing but there isn't any on the site anilist

**Comment by Sadwhy** [comment]
![Screenshot_20231210_091706_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/99601717/8403bb24-88da-4098-b98c-9d9ce1e67656)

**Comment by rebelonion** [comment]
> The browse anime doesn't find anything nor showing nsfw anime. I tried to enable nsfw setting if there were such thing but there isn't any on the site anilist

there is a setting on anilist too

**Comment by Sadwhy** [comment]
> The browse anime doesn't find anything nor showing nsfw anime. I tried to enable nsfw setting if there were such thing but there isn't any on the site anilist

If you haven't already enabled nsfw on anilist then

Tap on your pfp>setting>about>faq>how to enable nsfw content
You can enable it there.

**Comment by sombresu** [comment]
Thank you. But I'm not blind. There wasn't such check box nor enable nsfw in anilist site.

**Comment by rebelonion** [comment]
https://anilist.co/settings/media
enable 18+ content
