### ISSUE TITLE
Add "good first issue" tag to issues

### ISSUE THREAD

**Issue by germaniuss** [rebelonion/Dantotsu#87]
I've previously contributed to Saikou (though I only did one contribution) and am very glad the project is resurrected, the hard work is very appreciated!

I would like to contribute sometime in the future when I have free time but I am not sure which features are being worked on and which ones are still up for grabs, so a "good first issue" tag would be very appreciated.

Keep, doing this awesome job, you rock!

**Comment by Zaxx69** [comment]
You should join our discord ,you can see the things we are working on

**Comment by rebelonion** [comment]
good idea, but very few simple issues in github
there's more info on discord

**Comment by rebelonion** [comment]
not many, but done
