### ISSUE TITLE
Extension app download failure 

### ISSUE THREAD

**Issue by Kiethdavids1** [rebelonion/Dantotsu#92]
Whenever trying to download extension through the app it says installation failed unable to create directory any fix for this issue

**Comment by rebelonion** [comment]
all extension types?

**Comment by Kiethdavids1** [comment]
Yes from what I've experienced

**Comment by rebelonion** [comment]
Did you try the legacy installer?

**Comment by Kiethdavids1** [comment]
Yes it was already active

**Comment by rebelonion** [comment]
The error you gave does not make sense for anime and manga extensions.
For now you can try downloading those extensions from the aniyomi and tachiyomi website.

**Comment by Kiethdavids1** [comment]
I have been and those work. This is the exact error message I get through the app Installation failed: Unable to create directory: /storage/emulated/0/Android/data/ani.dantotsu/files/Download

**Comment by rebelonion** [comment]
Does this problem happen in Aniyomi or Tachiyomi, if you've tried?

**Comment by Kiethdavids1** [comment]
Tachiyomi is fine but the aniyomi app I click install on extension list and nothing happens

**Comment by rebelonion** [comment]
this is probably the same thing as #123 
try granting storage permission
Either way it's device specific ig
