### ISSUE TITLE
Remove one of these episode number from the video player

### ISSUE THREAD

**Issue by J4zzyB1te7s** [rebelonion/Dantotsu#94]
Is it possible to remove one these episode number cause two looks weird
![IMG_20231222_144157](https://github.com/rebelonion/Dantotsu/assets/126276749/2f732238-5118-45dd-a060-cb7c78ceebc1)

**Comment by rebelonion** [comment]
This is dependent on how the source sends the title, so not easily

**Comment by rebelonion** [comment]
If it bugs you, try another source
