### ISSUE TITLE
`snackString` is present for an annoyingly long time on hold to fastforward

### ISSUE THREAD

**Issue by KorigamiK** [rebelonion/Dantotsu#97]
I tend to use the fast forward feature on the player by pressing and holding to play at `2x` speed but the snackString annoys me too much as it lingers on for too long and appears 2 times (during press and after relesase).

![photo_2023-12-25_22-43-29](https://github.com/rebelonion/Dantotsu/assets/72932688/f165b0ee-4076-4ef3-87eb-4a81aafddb7b)

Maybe this call to the function can be removed or a better way to show a small `x2` in the corner of the ui would be a better option?

https://github.com/rebelonion/Dantotsu/blob/7ebb539bbabf86a85512b9f608c645494dadcd7f/app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt#L815C1-L828C14

**Comment by rebelonion** [comment]
I'll look into it

**Comment by rebelonion** [comment]
Will be fixed in the next beta
