### ISSUE TITLE
Tysm For This! Can you help me with something?

### ISSUE THREAD

**Issue by AkiraKusanagi** [rebelonion/Dantotsu#98]
Do you think I can get an Android TV/PS3-like icon of the Dantotsu app? I am making a customization thingy for Dantotsu on a Playstation 3/PSP inspired launcher. Sorry, this is pretty off-topic, it would be much appreciated! (The Dantotsu app on there has a tiny android icon...🤔) 
![Screenshot_20231227-015118](https://github.com/rebelonion/Dantotsu/assets/137284132/5cd02a47-4dab-44d7-963b-07ec41d1aaba)

**Comment by AkiraKusanagi** [comment]
Here's what I have for the background.
![Screenshot_20231227-025003](https://github.com/rebelonion/Dantotsu/assets/137284132/26a3ed90-e23e-4c29-a78c-bc8c86a60f68)

**Comment by AkiraKusanagi** [comment]
I made 2 icons for Android TV.
![IMG_20231227_035758](https://github.com/rebelonion/Dantotsu/assets/137284132/c94d44bf-e56e-4a38-8bf0-1f82e1ca5d89)
![IMG_20231227_035043](https://github.com/rebelonion/Dantotsu/assets/137284132/97fcbcb6-1dcd-428a-8c29-2edffd30e907)
Which would you prefer?

Anyways, I guess I'm done. (Tbh, I dunno why I posted this. That was kinda dumb, my bad!)
![Screenshot_20231227-041244](https://github.com/rebelonion/Dantotsu/assets/137284132/8391784f-ba7e-4833-9ed5-2078a72555b8)

**Comment by aayush2622** [comment]
added ty
